### ISSUE TITLE
Extraire la liste des utilisateurs par groupe de travail client

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#102]
Est-il possible de repartir de la [liste des groupes de travail](https://docs.google.com/spreadsheets/d/1U4Ku4XoddHaF64vKABv7A1zmWX-eQYqS4F0c5RtI0H8/edit#gid=0) utilisée pour la correction des évènements et d'exporter la liste des utilisateurs pour chaque groupe de travail ?

**Comment by SimonSAMPERE** [comment]
C'est fait, dis moi si ça te convient : https://docs.google.com/spreadsheets/d/1XKKP2ZqkeJ9poP3oqkIaN2iH2-bPQNvh/edit#gid=76674817
