### ISSUE TITLE
[MD_REF] - CD 45 Loiret 

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#103]
# Prestation de Métadonnées de Référence - CD 45 Loiret

Groupe cible : [4baf1fbdf4234d91b52c56978a292938](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/dashboard/formats)

Point de lancement : 05/01/2021 à 16h. Ce point servira à ajouter toutes les informations manquantes. **Les migrations seront lancées après ce point.**

Deadline : Pas de deadline définie

Contexte : Le Loiret est un client d'Isogeo depuis 2014. Le client qui n'hésite pas à poser des questions au besoin et à nous faire des retours quand en demande. Prestation de métadonnée de référence demandée directement à travers le marché négocié.

## Catalogues à migrer

- [**BD Topo 3.0** (54eb129b4dd840ada8de710994a310dc)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A54eb129b4dd840ada8de710994a310dc) vers [cca701ca405a4aff99f78cf38a22f63e](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Acca701ca405a4aff99f78cf38a22f63e) 
- [**BD Carto 4.0** (64571133cc4148baaad15c400e255fb4)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A64571133cc4148baaad15c400e255fb4) vers [6f4fb773dc5548e0aa880255bef1b0a7](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A6f4fb773dc5548e0aa880255bef1b0a7)
- [**Admin Express** (7dd4fd6da07f403ba4419390f3815362)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A7dd4fd6da07f403ba4419390f3815362) vers [3841690cd53f4003b663aed9ea48526c](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A3841690cd53f4003b663aed9ea48526c)
- [**Scan 25, Scan100, Scan état Major 40K et scan50 Historique** (1bd2dbd07aee4b0b8562be3d1a5f2206)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A1bd2dbd07aee4b0b8562be3d1a5f2206) vers [1e21fc8e9b4646d1a49e1a60ff56833f](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A1e21fc8e9b4646d1a49e1a60ff56833f)
- [**Contours IRIS** (ed92ea9a86f040a5b33dda469f69ffff)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Aed92ea9a86f040a5b33dda469f69ffff) vers [5094dc4087cc44e68ced3971e371f533](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A5094dc4087cc44e68ced3971e371f533)
- [**REG Alti** (de1506b69093461990f2b17c9275443c)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ade1506b69093461990f2b17c9275443c) vers [03c2718b2bb94cf78baa897e9ffb29f2](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A03c2718b2bb94cf78baa897e9ffb29f2)
- [**RPG** (d2ce4649ee204445956eefda43ba1f0b)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad2ce4649ee204445956eefda43ba1f0b) vers [fcfdb19c1dc84d9d90ffd881ce1f2c01](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Afcfdb19c1dc84d9d90ffd881ce1f2c01)
- [**FranceRaster** (d8516d47174247629a23a58a6ceff307)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad8516d47174247629a23a58a6ceff307) vers [0680bde5e2d24588bd2b32fe0a1fc5d6](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A0680bde5e2d24588bd2b32fe0a1fc5d6)
- [**Cadastre Arcopole** (393a7d657b33457bb9a2e58aa96057de)](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A393a7d657b33457bb9a2e58aa96057de) vers [034ff8af125d45b5bded0319bd4d507b](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A034ff8af125d45b5bded0319bd4d507b)
- [**ZICO, ZNIEFF, ZPS et ZSC/SIC** (d911cd07d6604fabbba1765c3f18b6b6)](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad911cd07d6604fabbba1765c3f18b6b6) vers [56c246511f2d4f82afd40272a9f93d29](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A56c246511f2d4f82afd40272a9f93d29)

## Critères de correspondance
*La plupart du temps, la correspondance se fait sur le critère du nom de la donnée. Dans cette rubrique il faut indiquer les informations nécessaires pour établir cette correspondance entre la fiche source (celle d'Isogeo) et la cible (celle du client). Par exemple : la nom de la fiche cible est préfixé, le nom de la cible et de la source n'ont pas la même casse...*
- **BD Topo 3.0** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [ARRONDISSEMENT_MUNICIPAL](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/23a46d3db9a5434fb9632863a026f93d/identification) |
| Cibles | CG_V_BDTOPO_45. | Majuscules | [CG_V_BDTOPO_45.HYDRO_PLAN_EAU](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/f48c4aacf6a44dc9ad797d5ce6b4e4c1/identification). |
- **BD Carto** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| sources | Pas de préfixe | Majuscule | [ZONE_HABITAT_MAIRIE](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/014c9126523b4dcb8aa7ac9c15972497/identification) |
| cibles | CG_V_BDCARTO. |Majuscules | [CG_V_BDCARTO.ENCEINTE_MILITAIRE](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/dfdab71d9a2743089e034440cef5265c/identification) |
- **Admin Express** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [ENTITE_RATTACHEE](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/05cb77b391ae47518b9f80a74cd6c6a8/identification) |
| Cibles | (CG_I_4_UNITES_ADMINISTRATIVES.ADMIN_EXPRESS_ | Majuscules | [CG_I_4_UNITES_ADMINISTRATIVES.ADMIN_EXPRESS_COMMUNE](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/dab9a0a34b734ef188fadf865ceb48f7/identification) |
- ***Scan 25, Scan100, Scan état Major 40K et scan50 Historique** : à dupliquer*
- **Contours IRIS** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [CONTOURS-IRIS](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/ee5a9e495b914c908a498aacd2aba960/identification) |
| Cibles | CG_I_4_UNITES_ADMINISTRATIVES.IGN_INSEE_ | Majuscules | [CG_I_4_UNITES_ADMINISTRATIVES.IGN_INSEE_CONTOUR_IRIS](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/ac48030f26d44359a94cbe306b9a808b/identification) |
- ***RGE Alti** : à dupliquer*
- ***FranceRaster** : à dupliquer*
- **RPG** : En attente du scan du client : il faudra migrer [cette fiche](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/6e5e8bec68b547dca5719c20342d9bb3/identification) dans toutes les fiches du catalogue [fcfdb19c1dc84d9d90ffd881ce1f2c01](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Afcfdb19c1dc84d9d90ffd881ce1f2c01)

- **Cadastre Arcopole** : 

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | aopcad. | Minuscules | [aopcad.lieudit](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/a98e5a9e8ae8425e81de8c4a729e9aba/identification) |
| Cibles | CG_I_6_CADASTRE. | Minuscule | [CG_I_6_CADASTRE.hydro](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/d7f96aa75c89475f9234bd273de4b043/identification) |
  - Cas particulier : données label (ou texte). Le nom des fiches sources contient "txt". Exemple : [aopcad.txt_hydr](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/504e42fa9fa64147a59af9fb29bea3ce/identification). Le nom des fiches cibles contient "label". Exemple [CG_I_6_CADASTRE.label_hydr](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/70eaec5389ac4dca93c6e021b080bd3e/identification)
- **ZICO** : **Ne pas migrer**
- **ZIEFF1 et ZNIEFF2** : 

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Minuscules | [znieff1](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/18c047b315654897b0b20938b4d094d0/identification) | 
| Cibles | CG_I_9_SITES_PROTEGES.DREAL_ | Majuscules | [CG_I_9_SITES_PROTEGES.DREAL_ZNIEFF1](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/f69421a3d00f4b5f992b97fff99b4d1c/identification) |
- **ZPS** : En attente du scan du client 

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Source | **Suffixe** 1712 | Minuscules | [zps1712](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/0ec485b6e259470c8265cf1f4ecada90/identification) |
| Cible | CG_I_9_SITES_PROTEGES.DREAL_ | Majuscules | [CG_I_9_SITES_PROTEGES.DREAL_NATURA2000_ZPS](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/7daf6af588654c909243cb830c2dceb2/identification) |
- **ZSC/SIC** : En attente du scan du client

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | **Suffixe** 1609 | Minuscules | [sic1609](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/958b44873ec743e0999378cb6047512f/identification) |
| Cibles | CG_I_9_SITES_PROTEGES.DREAL_NATURA2000_ | Majuscules | [CG_I_9_SITES_PROTEGES.DREAL_NATURA2000_PSIC](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/805e91f2b805494fa3a8b7f39b41169f/identification) |

## Règles de migration

**Ajouter le contact "Département du Loiret (CD 45)" en point de contact pour toutes les fiches**

- **BD Topo** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | Département des Pyrénées-Atlantiques | Département du Loiret |
| Exemple | Entités de transitions [BD TOPO®] - Département des Pyrénées-Atlantiques | Entités de transitions [BD TOPO®] - Département du Loiret |
- **BD Carto** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | Département du Loiret |
| Exemple | Zones d'habitat [BD CARTO®] - XXXX | Zones d'habitat [BD CARTO®] - Département du Loiret |
- **Admin Express** :

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | Département du Loiret |
| Exemple | Entités rattachées [ADMIN EXPRESS] - France Métropolitaine | Entités rattachées [ADMIN EXPRESS] - Département du Loiret |
- **Scan 25, Scan50, Scan état Major 40K et scan50 Historique** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | Département du Loiret |
| Exemple | Fond cartographique historique à l’échelle 1 : 50 000 [Scan 50® Historique] - France Métropolitaine | Fond cartographique historique à l’échelle 1 : 50 000 [Scan 50® Historique] - Département du Loiret |
- **Contours IRIS** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | Département du Loiret |
| Exemple | Contours des îlots regroupés pour l'information statistique [Contours IRIS®] - XXXX | Contours des îlots regroupés pour l'information statistique [Contours IRIS®] - Département du Loiret |
- **RGE Alti** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | Département du Loiret |
| Exemple | Modèle numérique de terrain de résolution 5 mètre [REG Alti®] - France Métropolitaine | Modèle numérique de terrain de résolution 5 mètre [REG Alti®] - Département du Loiret |
- **FranceRaster** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | Département du Loiret |
| Exemple | Fond cartographique à l’échelle 1 : 8 000 000 [FranceRaster®] - France Métropolitaine | Fond cartographique à l’échelle 1 : 8 000 000 [FranceRaster®] - Département du Loiret |
- **RPG** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | Département du Loiret |
| Exemple | lots anonymes [RPG®] - France Métropolitaine | lots anonymes [RPG®] - Département du Loiret |

Il faudra aussi ajouter le millésime au titre des différentes fiches en fonction de l'année qui figure dans le nom de la fiche cible. 

Exemple : 
| Donnée cible | Titre |
|--- | --- |
| [CG_II_2_OCCUPATION_TERRE.REGISTRE_PARCEL_GRAPHIQUE_2018](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/e41c9f8631a447438a36c77d0c14be30/identification) | lots anonymes [RPG®] - Département du Loiret - 2018 |
- **Cadastre Arcopole** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | Département du Loiret |
| Exemple | Hydrographie (Texte) [Cadastre Arcopole] - XXXX | Hydrographie (Texte) [Cadastre Arcopole] - Département du Loiret |
- **ZICO, ZNIEFF, ZPS et ZSC/SIC** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | Région Centre-Val de Loire |
| Exemple | Zones naturelles d'intérêt écologique, faunistique et floristique continentales de type 2 [ZNIEFF] - France Métropolitaine | Zones naturelles d'intérêt écologique, faunistique et floristique continentales de type 2 [ZNIEFF] - Région Centre-Val de Loire |

## Suivi

- [x] **BD Topo 3.0** : Donnée scannée | Attente de la table de correspondance | Go!
- [x] **BD Carto** : Donnée scannée | Go!
- [x] **Admin Express** : Donnée scannée | Go!
- [x] **Scan 25, Scan100, Scan état Major 40K et scan50 Historique** : Go!
- [x] **Contours IRIS** : Donnée scannée | Go!
- [x] **RGE Alti** : Go!
- [x] **FranceRaster** : Go!
- [x] **RPG** : Donnée scannée | Go!
- [x] **Cadastre Arcopole** : Donnée scannée | Go!
- [x] **ZICO** : **Ne pas miger**
- [x] **ZIEFF** : Donnée scannée | Go!
- [x]  **ZPS** : Donnée scannée | Go!
- [x] **ZSC/SIC** : Donnée scannée | Go!

**Comment by Mouzzi-C** [comment]
@SimonSAMPERE, je t'ai modifié le ticket. Tu peux commencer à migrer les catalogues 👍

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C  ok super, je vais commencer par faire les tables de correspondance et je reviens vers toi.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C j'ai géénré une première table de correspondances [(correpondances_v1.csv)](https://drive.google.com/drive/folders/1Em-0nXfPhXu6Sboxxv2_UVfERv7sjK9r) pour les catalogues à migrer, je te laisser regarder de ton côté, on pourra en discuter avant de contacter le client.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, les Scans, France Raster et le RGE Alti ont été migrés, je te laisse checker.

**Comment by Mouzzi-C** [comment]
> @Mouzzi-C j'ai géénré une première table de correspondances [(correpondances_v1.csv)](https://drive.google.com/drive/folders/1Em-0nXfPhXu6Sboxxv2_UVfERv7sjK9r) pour les catalogues à migrer, je te laisser regarder de ton côté, on pourra en discuter avant de contacter le client.

Je t'ai complété la table de correspondance. 

Tu peux lancer la migration pour tout sauf les champs en rouge (donc la bd carto (je dois vérifier la version souhaitée avec le client) et RPG (pas encore scanné)). Ne prends pas en compte les fiches sources qui n'ont pas de fiches cibles

**Comment by SimonSAMPERE** [comment]
On est d'accord qu'il faut donc migrer : 
* 5 fiches de ma BD TOPO 3.0
* 8 fiches d'Admin Express
* 18 fiches de Cadastre Arcopole
Tu confirmes @Mouzzi-C ?

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C c'est quoi la prochaine étape ?

**Comment by Mouzzi-C** [comment]
J'attend les scan du client. Je te dis dès que c'est bon mais ça a l'air tendu en ce moment côté client

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C le catalogue source indiqué pour ZICO, ZNIEFF, ZPS et ZSC/SIC ne semble pas exister

**Comment by SimonSAMPERE** [comment]
Le deuxième round de la prestation a été effectué aurjourd'hui, je te laisse checker.
