### ISSUE TITLE
Métropole Aix Marseille Provence - Ajouter les liens vers l'extracteur Veremes aux fiches de métadonnée

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#104]
### Contexte

La métropole Aix Marseille Provence, client Isogeo, a mis en place un extracteur basé sur l'outil [GTF de Veremes](https://www.veremes.com/produits/gtf). L'extracteur est accessible via une interface Web. Un script a été développé côté extracteur pour récupérer auprès de l'API Isogeo la fiche XML au moment de l'extraction d'une donnée. Il s'agit maintenant de faire l'inverse, c'est à dire d'indiquer le lien d'extraction de la donnée dans la fiche de métadonnée. 

Nous avons donc vendu 1 jour de dev + 1 jour de gestion de projet pour cette prestation. Il faudra mettre en bleu dans ce [tableau ](https://docs.google.com/spreadsheets/d/1-9e75f-qqGNln8_3oBl4nvocW3ZwCT3Jho9UKxhEo4k/edit#gid=0)les deux lignes correspondantes à cette prestation lorsqu'elle sera réalisée.

### Objectif du script

Générer pour chaque fiche de métadonnée un lien de téléchargement de la donnée comme sur cette [fiche](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/8ea16a7b7ab042fc8156f6431efaf5ec/resources). 

### Construction des url(s)

L'URL est composée de l'url de base + l'attribut layer contenant le nom de la couche

**Exemple :** https://geodata.ampmetropole.fr/?mode_id=extraction&layer=aopcad.bati

Le nom de la couche correspond au nom de la table dans la fiche de métadonnée. 
La liste des tables concernée est stocké dans le [drive](https://drive.google.com/drive/u/0/folders/1sd04rvXfUCqr4F6ClfguJvCxU3HarLAT).

### Etapes

- [x] Lire le fichier _rt_layer_export_151220201000.csv_ contenant les noms des tables concernés (colonne _layer_id_)
- [x] Rechercher la fiche de métadonnées correspondante dans l'inventaire du groupe de travail de Marseille [e3a3412cae2843c997862f9d18857dfc](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/inventory/search?p=1&ob=%23relevance&od=des)
- [ ] Etablir les correspondances manquantes
- [ ] Ecrire l'url de téléchargement de la donnée (type _url | data | download_)
- [ ] Ajouter le catalogue U_Extracteur (d220c42c6b4c4dbd8b068dde32579b58)
- [ ] Faire vérifier par le client
- [ ] Valider la prestation dans le [tableau de suivi](https://docs.google.com/spreadsheets/d/1-9e75f-qqGNln8_3oBl4nvocW3ZwCT3Jho9UKxhEo4k/edit#gid=0)

**Comment by SimonSAMPERE** [comment]
Dans la liste des table, certains noms correspondent à l'emplacemenet donnée fichier et pas à une table, par exemple "\\\\appgtf\\RASTER\ortho10cm2018\\mamp-10cm-ortho2018.jp2" ou "\\\\appgtf\\RASTER\\scan\\SCAN25_TOUR_PACA1.tif".

Que faire dans ce cas ?
 - [ ] prendre le nom du fichier à la place du nom de la table
 - [ ] ne pas créer le lien
 - [ ] autre chose

**Comment by leodarengosse** [comment]
Je n'ai pas la réponse à cette question, je fais un point avec le client à la rentrée et je te dis, en attendant combien tu as de table pour lesquelles cela match bien ?

**Comment by SimonSAMPERE** [comment]
A première vu, je retrouve 115 fiches de métadonnées à partir des 580 noms présents dans le tableau.

**Comment by leodarengosse** [comment]
Ah ouais ça fait pas beaucoup...Tu peux me faire un export avec les couches qui matchent et celles qui matchent pas stp ?

**Comment by SimonSAMPERE** [comment]
[`extraction_link_matching.csv`](https://drive.google.com/drive/u/0/folders/1sd04rvXfUCqr4F6ClfguJvCxU3HarLAT)

**Comment by SimonSAMPERE** [comment]
On passe à 218 correspondances si on ne tient pas compte de la casse, j'ai mis à jour [la table](https://docs.google.com/spreadsheets/d/1XSCstjkNm7PRftF7g2-3bRfqi8S-y0fp/edit#gid=1737641005).

**Comment by leodarengosse** [comment]
je vais renvoyer ce tableau de correspondance au client au cas ou il y ait un soucis avec les tables restantes

**Comment by leodarengosse** [comment]
j'ai modifié le tableau ajout_lien_extracteur_rapport_v3.xlsx avec la dernière donnée manquante (tramob.tramob_res_parking_relais_p_amp). 

La table de correspondance est maintenant complete et l'import peut être effectué.

**Comment by SimonSAMPERE** [comment]
Super je lance ça dès que possible.

**Comment by SimonSAMPERE** [comment]
@leodarengosse , du coup j'ai lancé le script pour créer le lien dans 397 fiches pour lesquelles j'ai pu établir le matching en me basant sur le nom indiqué. Pour les 47 restantes, je vais relancer le script en me basant sur l'UUID indiqué dans le tableau ajout_lien_extracteur_rapport_v3.xlsx du drive. Mais du coup pour générer l'URL je me base sur le nom indiqué dans le tableau ou sur le nom de la donnée apparaissant dans la fiche de métadonnées ?
