### ISSUE TITLE
Remplacement de licence et duplication de catalogue

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#107]
## Remplacer la licence
Il faudrait remplacer la [Licence IGN - Mission de service public](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/admin/licenses/34f800d2370a43d2a1681eb2397b0dd3)  des fiches des catalogues suivant par la [Licence ouverte ETALAB 2.0](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/admin/licenses/f6e0c665905a4feab1e9c1d6359a225f) : 

- [BD Ortho - 473e22ebfa964254a9dac715f96fa55e](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A473e22ebfa964254a9dac715f96fa55e)
- [Routes 500 - 0bd42e9d5a724704ab17127168262a85](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A0bd42e9d5a724704ab17127168262a85)
- [BD Topo 3.0 - 54eb129b4dd840ada8de710994a310dc](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A54eb129b4dd840ada8de710994a310dc)
- [BD Carto 3.3 - 3f518621e6de4bda9eafb03a9ab27e60](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A3f518621e6de4bda9eafb03a9ab27e60)
- [BD Parcellaire - b8c94091f63748cf9245754b9cc35295](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ab8c94091f63748cf9245754b9cc35295)

## Dupliquer la BD Carto
Ensuite, il faudrait dupliquer la [BD Carto 3.3 - 3f518621e6de4bda9eafb03a9ab27e60](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A3f518621e6de4bda9eafb03a9ab27e60) dans le catalogue [BD Carto 4.0 - 64571133cc4148baaad15c400e255fb4](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A64571133cc4148baaad15c400e255fb4)

**Comment by SimonSAMPERE** [comment]
Script exécute, @Mouzzi-C je te laisse vérifier le résultat et me dire si j'ai fait une boullette
