### ISSUE TITLE
[Val-de-Marne] Générer un table de correspondance fiches APP/fiches OC

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#108]
## Contexte
Suite à une migration de 683, les fiches OC des fiches sources sont toutes devenues obsolète. 

## Table de correspondance
Pour chaque fiche du catalogue [M_Migrated](https://app.isogeo.com/groups/3dc29ce36d9d4b969a08e8669301c751/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Aac50a4b41219421ab05c6a5616793f50) associée au partage [Géocatalogue SIG94](https://app.isogeo.com/groups/3dc29ce36d9d4b969a08e8669301c751/admin/shares/54c4a64f736d4499840d5c7a129fbc7d), générer une table de correspondance qui inclue  : 

- Le lien dans APP
- Le lien de l'OC correspondant

**Comment by SimonSAMPERE** [comment]
Je pense que ça doit être faisable en faisant un export excel du catalogue via Isogeo2Office et en utilisant la [fonction de concatenation d'Excel](https://support.microsoft.com/fr-fr/office/concatener-concatener-fonction-8f8ae884-2ca8-4f7a-b093-75d702bea31d) pour générer l'url de la fiche dans app à partir de son uuid.

**Comment by Mouzzi-C** [comment]
Au fait il suffit de faire un export sur I2O et récupérer les liens de l'OpenCatalog tel quel. J'attends la réponse du client pour savoir quels sont les partages pour lesquels il voudrait faire ça.

Tu peux close cet issue si tu penses qu'il n'est plus nécessaire qu'il soit ouvert.

**Comment by Mouzzi-C** [comment]
C'est bon, je envoyé [la table suivante](https://docs.google.com/spreadsheets/d/1N0qw8XceffdhTyAdpACEh3ujA4E7v6oPH191QApCDOc/edit#gid=0).

Je ferme l'issue.

**Comment by SimonSAMPERE** [comment]
Bien joué !
