### ISSUE TITLE
[MIGRATION] - Saint-Lô (Doublons du scan)

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#113]
# Listing de doublons puis migration et ménage
Faire un listing de tous les doublons des données postgis du gt.

Groupe cible : [f71fd5294d454482aa42fe143556c503](https://app.isogeo.com/groups/f71fd5294d454482aa42fe143556c503/dashboard/formats)

Deadline : Commencer à partir de la semaine du 22/03

Contexte : Doublons créés par le scan sur une base PostGIS.

## Catalogues

- [ ] Catalogue Cible :
  * *M_Migrated* : [12135067669745a5a6497c0579e5b3a9](https://app.isogeo.com/groups/f71fd5294d454482aa42fe143556c503/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A12135067669745a5a6497c0579e5b3a9)

## Critères de correspondance

Lancer le script sur toutes les fiches de données **PostGIS** du GT pour déterminer celles qui ont le même nom.

**Comment by SimonSAMPERE** [comment]
J'ai généré une table de mapping [ici](https://docs.google.com/spreadsheets/d/1Z6kzcgvqOYXt3sTpbx2LzHVgznlxQVzK/edit?usp=drive_web&ouid=107937934076694281279&rtpof=true). Elle contient une ligne par nom de données PostGIS récupéré dans le groupe de travail. Lorsqu'une seule fiche correspond à un nom, la colonne "newer" contient l'uuid de la fiche" et la colonne "older" prend la valeur "no_duplicate". Lorsque deux fiches correspondent à un nom, la colonne "newer" contient l'uuid de la fiche créée le plus récemment et la colonne "older"contient l'uuid de la seconde (la plus ancienne).

@Mouzzi-C , je te laisse y jetter un coup d'oeil pour investiguer.

**Comment by Mouzzi-C** [comment]
Message du client au sujet de la modification de la base postgis :

En dehors de la suppression de la fonction spatiale en double dans la base de données j'ai proccédé à une ré indexation des tables à l'aide du script suivant qui liste les tables en fonction des schémas et qui permet de re générer d'un coup tous les index sur les tables.

 

-----

SELECT table_schema || '.' || table_name as fqntable,

       'CREATE INDEX ' || table_name || '_' || column_name || '_gist on ' || table_schema  || '.' || table_name || ' using gist(' || column_name || ');' ||

       'ALTER TABLE ' || table_schema  || '.' || table_name || ' CLUSTER ON ' || table_name || '_' || column_name || '_gist;'

FROM   information_schema.columns

WHERE  udt_name = 'geometry'

       -- on filtre pour ne garder que les tables qui n'ont pas d'index gist

       AND table_schema || '.' || table_name not in (

           SELECT N.nspname || '.' || I.tablename

           FROM pg_class C

           JOIN   pg_am AM          ON  C.relam = AM.oid

           LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)

           LEFT JOIN pg_tables    T ON (T.tablename = C.relname)

           LEFT JOIN pg_indexes   I ON (I.indexname = C.relname)

           WHERE nspname NOT IN ('pg_catalog','pg_toast','information_schema') and AM.amname= 'gist'

       )

       -- on ne garde que les tables, les vues sont exclues

       AND table_schema || '.' || table_name NOT IN (

           SELECT schemaname || '.' || viewname

           FROM pg_views

       )

AND table_schema='pci'

------

**Comment by SimonSAMPERE** [comment]
@leodarengosse, tu m'avais parlé d'une presta de nettoyage globale je crois, est-ce-que ça impact le déroulement de cette migration de doublons ?

**Comment by Mouzzi-C** [comment]
Non tu peux y aller pour cette migration. On est pas sûr de recevoir la commande pour le nettoyage global

**Comment by SimonSAMPERE** [comment]
ok super je fais ça pendant ce sprint

**Comment by SimonSAMPERE** [comment]
340 doublons ont été migrés : https://app.isogeo.com/groups/f71fd5294d454482aa42fe143556c503/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A12135067669745a5a6497c0579e5b3a9 conformément à [cette table](https://github.com/isogeo/migrations-toolbelt/files/6403878/mapping_final.xlsx) (G:\Mon Drive\Racine Isogeo\Clients\34_CA_SAINT_LO_AGGLOMERATION\3_REALISATION\3_Catalogage\Migration doublons\mapping_final.xlsx).

Je te laisse cheker le résultat (surtout que j'ai bien migré le métadonnées dans les fiches qui seront actualisées par le scan) et j'attends ton feu vert pour supprimer le sources.
