### ISSUE TITLE
Nettoyage du GT de CD 27 - Eure

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#115]
## Contexte 
L'Eure est client Isogeo depuis plusieurs déjà mais cela fait quelques années que l'outil n'est pas utilisé. Avec leur nouvel environnement ils veulent relancer le processus de documentation donc reprendre de zéro (ou presque).

## Deadline
À partir de la semaine du 05/04

## Groupe de Travail
[9d29b7ec6d854f7580bb3eb5107dcad1](https://app.isogeo.com/groups/9d29b7ec6d854f7580bb3eb5107dcad1/dashboard/formats)

## Exceptions
il faudra garder :
- Les fiches ressources
- la fiche : [Registre   Parcellaire Graphique 2014](https://app.isogeo.com/groups/9d29b7ec6d854f7580bb3eb5107dcad1/resources/e048fe876272488d8c016b5e4f9c0df3/identification)
- la fiche : [Les espaces   naturels sensibles de l'Eure](https://app.isogeo.com/groups/9d29b7ec6d854f7580bb3eb5107dcad1/resources/0835b0f527344f0cbcda041193a0598d/identification)
- la fiche : [Zones de Protection   Spéciale (ZPS) - Natura 2000](https://app.isogeo.com/groups/9d29b7ec6d854f7580bb3eb5107dcad1/resources/cc904d72141441609afef2e49d9470df/identification)

**Comment by Mouzzi-C** [comment]
Il faut supprimer les toute fiches les fiches à l'exception des quelques fiches mentionnées dans l'issue

**Comment by SimonSAMPERE** [comment]
Ok j'essaye de faire ça pendant ce sprint, je te tiens au courant.
