### ISSUE TITLE
Monaco - Import CSV de métadonnées

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#116]
**Contexte**

Le client Monaco a exporté les métadonnées saisies dans leur Geodatabase d'entreprise SDE au format CSV. Le but est donc de les importer dans leurs métadonnées scannées dans Isogeo.

- Groupe concerné : deb0fa5d802f4841ba04e8707ba994d7
- Dossier Drive : G:\Mon Drive\Racine Isogeo\Clients\91_MONACO\04_REALISATION\04_CATALOGAGE
- Delai : avant la formation du **9 avril** si possible
- Catalogue cible : 694bd8ad97994c2eab24ed2651822ed6

**Données en entrée**

Deux tableaux ont été exportés. Le premier contient les métadonnées de couches (Monaco_metadata.csv) et le deuxième contient les attributs et leurs alias (Monaco_Champs_PROD.csv).

Le premier contient les champs suivants  

- name : nom de la table pour effectuer la correspondance
- summary : résumé à mettre dans la fiche cible
- tags : mots clés à affecter à la fiche cible (séparés par une virgule)
- conditions : ajouter la condition Gouvernement de Monaco ([08bb55009bf54d2d8f9092d8a1e382d9](https://app.isogeo.com/groups/deb0fa5d802f4841ba04e8707ba994d7/admin/licenses/08bb55009bf54d2d8f9092d8a1e382d9)) à la fiche cible
- proprietaire : ajouter le contact du carnet d'adresse ayant le même nom avec le rôle Propriétaire (ex : [IMSEE - Alexandre Bubbio](4c571fe899ea40af84f4d97fc73166bc))
- administrateur : ajouter le point de contact du groupe de travail Gouvernement de Monaco avec le rôle Administrateur 
- !!! NE PAS AJOUTER LE CONTACT SI IL EST DEJA AFFECTE A LA FICHE !!!

Le second contient les champs suivants 

- TABLE : nom de la table
- NAME : nom du champ
- ALIAS : alias à indiquer dans le champs alias de la fiche cible

**Etapes** 

- [x] Créer la table de correspondance pour les métadonnées
- [x] Importer les champs ci-dessus dans les fiches
- [x] Créer la table de correspondance pour les attributs (au passage vérifier que les attributs existent bien tous)
- [ ] Import les alias d'attributs

**Comment by SimonSAMPERE** [comment]
La table de correspondance est dans le dossier drive (G:\Mon Drive\Racine Isogeo\Clients\91_MONACO\04_REALISATION\04_CATALOGAGE).

**Comment by leodarengosse** [comment]
**Corrections** 

- Ne pas importer les titres
- Mettre le rôle Propriétaire au contact Propriétaire

**Comment by SimonSAMPERE** [comment]
@leodarengosse, concernant les attributs, j'ai lancé un premier script de matching dont le résultat est le fichier [`correspondances_Champ.xlsx`](https://docs.google.com/spreadsheets/d/1dwH9Ay0hLd5jkbi9ZqQhduG6ogRqJGBb/edit#gid=735597818) (dans "G:\Mon Drive\Racine Isogeo\Clients\91_MONACO\04_REALISATION\04_CATALOGAGE"). N'hésite pas à me le dire si le fichier n'est pas claire.

**Comment by leodarengosse** [comment]
@SimonSAMPERE tu peux Importer uniquement les alias qui sont différents des noms des champs en ne prenant pas en compte la casse. Seule la chaine de caractère compte. 

Pour les fiches et les attributs sans correspondance, on laisse tomber !
