### ISSUE TITLE
Marseille - Import Excel

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#122]
**Ticket en cours de rédaction**

# Contexte

Groupe concerné : e3a3412cae2843c997862f9d18857dfc
Dossier Drive : G:\Mon Drive\Racine Isogeo\Clients\78_Métropole de Marseille - AMP\05_REALISATION\01_CATALOGAGE\Intégration Excel\A importer
Délai : début juin
Catalogue cible : [b918f8b6c2be48e799131b9b4dc29f84](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ab918f8b6c2be48e799131b9b4dc29f84)

# Donnée en entrée

Un tableau Excel (_CT5_maj042021_CC.xlsx) contenant les champs suivants à importer

Titre
Résume
Mots-clés
Thématiques INSPIRE
Contexte de collecte
Méthode de collecte
Début de validité --> Date de création
Fin de validité --> date de mise à jour
Commentaire
Contact : le nom du contact correspond à un contact du carnet d'adresses ; l'ajouter aux fiches avec le rôle propriétaire

# Critères de migration (début et fin de validité)
Deux scénarios sont possibles : 
1. Lorsque la date de début de validité et la date de fin de validité est la même:
   * ne pas remplir les champ validFrom et validTo
   * ajouter un événement de création de la fiche avec cette date
   *Exemple : dechet.dechet_coll_pact_2012_ct5_s --> date de création 01/01/2012*
2. Lorsque la date de début de validité et la date de fin de validité est différente:
   * ne pas remplir les champ validFrom et validTo
   * ajouter un événement de création de la fiche avec la date de début de validité
   * ajouter un événement d'update de la fiche avec la date de fin de validité

# Etapes

- [x] Créer la table de correspondance avec le catalogue CT5
- [x] Importer les champs de métadonnées ci-dessus

**Comment by Mouzzi-C** [comment]
Il faudra générer une première table de correspondance 
* nom technique source de [ce tableau](https://docs.google.com/spreadsheets/d/1y77ti2ZLZY43YKoQj_BHQhe_bVLUOjLg/edit#gid=386460340). 
* Fiches cibles : toutes les fiches du GT [e3a3412cae2843c997862f9d18857dfc](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/inventory/search?p=1&ob=%23relevance&od=des)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C j'ai généré un petit [rapport de matching](https://docs.google.com/spreadsheets/d/1fDOuizNCcwp1ZoHRaKCXWNhLOC1tsUcnHoDZyxC_qYE/edit#gid=0) à partir du tableau. J'ai repéré plusieurs cas possibles : 
* le nom indiqué dans le tableau correspond à une des fiches du groupe (**name_match**=1) :
  * aucun uuid n'est indiqué dans le tableau, j'ai récupéré celui de la fiche dont le nom match (**ready for import**=1)
  * l'uuid indiqué dans le tableau correspond à la même fiche (**ready for import**=1)
  * l'uuid indiqué dans le tableau ne correspond pas à la même fiche (**ready for import**=0)
* le nom indiqué dans le tableau ne correspond pas à une des fiches du groupe (**name_match**=0 et **ready for import**=0)

hésite pas à organiser un point pour qu'on en discute avant de répondre au client

**Comment by leodarengosse** [comment]
@Mouzzi-C où en est-on à ce sujet svp ?

**Comment by Mouzzi-C** [comment]
On est bloqué à cause d'un problème de scan sur certaines données

**Comment by SimonSAMPERE** [comment]
métadonnées importées pour les 42 fiches matchées

**Comment by SimonSAMPERE** [comment]
métadonnées importées pour les 33 fiches restantes

**Comment by Mouzzi-C** [comment]
ok super, je vais informer le client 👍
