### ISSUE TITLE
[MIGRATION] - Reims

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#133]
# Prestation de Migration - Reims

Groupe cible : [aab0084b59d54847a9a65b0cd75194fd](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/inventory/search?p=1&ob=%23relevance&od=des)

Deadline :  

## Catalogues

- [ ] les catalogues Source et Cible existent:
  * *Nom du catalogue source* : [26d2111b06fb4bb1a667c0f83ce3cc3f](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A26d2111b06fb4bb1a667c0f83ce3cc3f)
  * *Nom du catalogue cible* : [ff31bcead09a4ab69d01359cc4893c90](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Aff31bcead09a4ab69d01359cc4893c90)
  * *M_Migrated* : [486da55694e34942b35ce5f3e487d3e4](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A486da55694e34942b35ce5f3e487d3e4)

- [ ] les catalogues n'existent pas : *indiquer une piste pour distinguer les fiches source des fiches cible. Par exemple : la date de dernière mise à jour de la fiche.*

## Critères de correspondance

Les fiches sources et cibles ont le même nom.

Exemple : 

| Fiche source  | Fiche cible |
|---|---|
| plan_agglo.cours_eau | plan_agglo.cours_eau |

## Règles de migration (si nécessaire)

Tout migrer

## Suivi

- [x] table de correspondance : Erreur du scan à régler avant de pouvoir lancer la table de correspondance
- [x] migration : *en attente du retour du client*
- [ ] suppression des fiches source : *en attente du client*

**Comment by Mouzzi-C** [comment]
J'ai enlevé le stand-by par ce que je devrais avoir plus d'infos d'ici lundi. On pourra lancer la migration dans la foulée si t'as le temps

**Comment by Mouzzi-C** [comment]
[Table de correspondance.xlsx](https://github.com/isogeo/migrations-toolbelt/files/6821286/Table.de.correspondance.xlsx)
voilà la table de correspondance actuelle. Ils relancer un scan avant de faire les correspondances restantes.

**Comment by SimonSAMPERE** [comment]
Ok donc les cibles et les source n'ont pas le même nom en fait ?

**Comment by Mouzzi-C** [comment]
C'est le cas pour le moment. À voir si ça le sera toujours avec les nouvelles données scannées.

**Comment by Mouzzi-C** [comment]
J'ai réalisé la migration manuellement et ai livré au client. 

En attente de la confirmation du client.

**Comment by SimonSAMPERE** [comment]
Le man est trop chaud
