### ISSUE TITLE
[MD_REF] - GPM du Havre

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#136]
# Prestation de Métadonnées de Référence

Groupe cible : [4b729516af434ba0b2c816216440a6ad](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/dashboard/formats)

Deadline : Pas de deadline précise.

Contexte : Il viennent de réinstaller le scan. Reprenne le catalogage. Ils vont devoir faire un peu de ménage de leur côté avant de pouvoir commencer à scanner les données. Ça devrait être fait d'ici mi juillet. (nous sommes le 23/06, let's see how this goes !)

### IGN-F (504f49055abc4d0b9865038fbc99b44b)
| Catalogue source | Catalogue cible |
| --- | ---- |
| [**BD Topo 3.0** (54eb129b4dd840ada8de710994a310dc)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A54eb129b4dd840ada8de710994a310dc) | [c8ae361f042846f98de8743ad0c1703d](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ac8ae361f042846f98de8743ad0c1703d) |
| [**BD Carto 4.0** (64571133cc4148baaad15c400e255fb4)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A64571133cc4148baaad15c400e255fb4) | [d49b5d1424054eeabbb0a3ddce7de681](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad49b5d1424054eeabbb0a3ddce7de681) |
| [**BD Parcellaire** (b8c94091f63748cf9245754b9cc35295)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ab8c94091f63748cf9245754b9cc35295) | [192dbf11d574491ba96e6c24d64f52d8](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A192dbf11d574491ba96e6c24d64f52d8) |
| [**Admin Express** (7dd4fd6da07f403ba4419390f3815362)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A7dd4fd6da07f403ba4419390f3815362) | [7b9ba337783a47eabfbdd476d77570db](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A7b9ba337783a47eabfbdd476d77570db) |
| [**Route500** (0bd42e9d5a724704ab17127168262a85)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A0bd42e9d5a724704ab17127168262a85) | [0c13cbfd25cc4e0eacdee4d77c3b7f4b](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A0c13cbfd25cc4e0eacdee4d77c3b7f4b) |
| [**Route120** (033edcf9977447ad99e614a166995027)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A033edcf9977447ad99e614a166995027) | [52fba5617ee64f02be0acbabc1d78ee6](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/admin/catalogs/52fba5617ee64f02be0acbabc1d78ee6) |
| [Scan 25 (1bd2dbd07aee4b0b8562be3d1a5f2206)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A1bd2dbd07aee4b0b8562be3d1a5f2206) | [31cbf5b1caea466e825a5482907a9c5b](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A31cbf5b1caea466e825a5482907a9c5b) |
| [Scan Express (7d49c596550e46e899f51a15b4a91dbe)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A7d49c596550e46e899f51a15b4a91dbe) | [31cbf5b1caea466e825a5482907a9c5b](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A31cbf5b1caea466e825a5482907a9c5b) |
| [**Contours IRIS** (ed92ea9a86f040a5b33dda469f69ffff)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Aed92ea9a86f040a5b33dda469f69ffff) | [d37f7037e20b452ca81f89bd161d21ab](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad37f7037e20b452ca81f89bd161d21ab) |
| [**RPG** (d2ce4649ee204445956eefda43ba1f0b)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad2ce4649ee204445956eefda43ba1f0b) | [31b89f63ba9c4b2489b7c1bad7748d4b](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A31b89f63ba9c4b2489b7c1bad7748d4b) |  
| [**BD Alti** (469183c049084cb381b80766e63accdf)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A469183c049084cb381b80766e63accdf) | [911bf2c03ba94a24881b64da4a740abb](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A911bf2c03ba94a24881b64da4a740abb) |
| [**RGE Alti** (de1506b69093461990f2b17c9275443c)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ade1506b69093461990f2b17c9275443c) | [fbde237b5ce14289804bc58062587a26](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Afbde237b5ce14289804bc58062587a26) |
| [**FranceRaster** (d8516d47174247629a23a58a6ceff307)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad8516d47174247629a23a58a6ceff307) | [5e53aaf50ae74d77a6beee1ce5bdd0e4](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A5e53aaf50ae74d77a6beee1ce5bdd0e4) |
| [**OCS GE** (751c2ef36ec84923982567657e18a0c6)](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A751c2ef36ec84923982567657e18a0c6) | [4135a787446941bf93572566fdef11c7](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A4135a787446941bf93572566fdef11c7) |

 ### DGFIP (98b00a0db4ab411995ce08f6a47eb8a7)
 
| Catalogue source | Catalogue cible |
| --- | ---- |
| [**Cadastre Etalab - Version Complète**(59dfcc70a0514414822919cee96140fc)](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A59dfcc70a0514414822919cee96140fc) | [23651a87112f47d8a2090a5697a8a958](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A23651a87112f47d8a2090a5697a8a958) |
| [**Cadastre Arcopole** (393a7d657b33457bb9a2e58aa96057de)](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A393a7d657b33457bb9a2e58aa96057de) | [17b88f2a2adb4ce6b6eec456b679721e](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A17b88f2a2adb4ce6b6eec456b679721e) |

### INPN (4380a3dd30df481aa19c7883e8ddee0d)

| Catalogue source | Catalogue cible |
| --- | ---- |
| [**ZICO, ZNIEFF, ZPS et ZSC/SIC** (d911cd07d6604fabbba1765c3f18b6b6)](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad911cd07d6604fabbba1765c3f18b6b6) | [09f240ccf1844c9a92672d863a17a491](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A09f240ccf1844c9a92672d863a17a491) |

## Critères de correspondance

- **BD Topo 3.0** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [ARRONDISSEMENT_MUNICIPAL](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/23a46d3db9a5434fb9632863a026f93d/identification) |
| cibles | Pas de préfixe | Majuscules | [TRONCON_DE_ROUTE](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/3bf1874cbc364c8787c8a5584fd8f1e3/identification) |
- **BD Carto** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| sources | Pas de préfixe | Majuscule | [ZONE_HABITAT_MAIRIE](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/014c9126523b4dcb8aa7ac9c15972497/identification) |
| cibles | Pas de préfixe | Majuscule | [ZONE_HABITAT_MAIRIE](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/d89ff81245ca4ea0a70001d6aa708aa0/identification) |
- **BD Parcellaire** : (à mettre à jour et vérifier)

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [BATIMENT](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/6ad5e6a2b82145968ffbe6c10998c733/identification) |
| cibles | Pas de préfixe | Majuscules | [BATIMENT](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/69df7e11030e40a0bdd94d61ba27ee99/identification) |
- **Admin Express** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [ENTITE_RATTACHEE](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/05cb77b391ae47518b9f80a74cd6c6a8/identification) |
| cibles |Pas de préfixe | Majuscules | [ENTITE_RATTACHEE](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/03de8cf427e2478e8bf952c18d8bfdaf/identification) |
- **Route500**

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [TRONCON_ROUTE](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/022c27dea19d4657b65eba4eeec863e9/identification) |
| cibles | Pas de préfixe | Majuscules | [TRONCON_ROUTE](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/a96d268794874d6eafb84d0dc8ec7297/history) |
- **Route12O**

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [ZONE_OCCUPATION_SOL](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/8630dcdb345d40949b82e8cfcce748fa/identification) |
| cibles | Pas de préfixe | Majuscules | [ZONE_OCCUPATION_SOL](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/e684209c87fe495d843be7c3804a592c/history) |
- ***Scan 25, Scan Express***  : à dupliquer*
- **Contours IRIS** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [CONTOURS-IRIS](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/ee5a9e495b914c908a498aacd2aba960/identification) |
| cibles | Pas de préfixe | Majuscules | [CONTOURS-IRIS](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/ee5a9e495b914c908a498aacd2aba960/identification) |
- ***RPG*** : à dupliquer
- ***BD Alti** : à dupliquer*
- ***RGE Alti** : à dupliquer*
- ***FranceRaster** : à dupliquer*
- **OCS GE** : 

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [OCCUPATION_SOL](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/b4d2485ce93f4dc2b33f409fe34b5491/identification) |
| cibles | *ajouter le préfixe* | *ajouter la casse* | *Ajouter un exemple* |
- **Cadastre Etalab - Version Complète** : 

| Fiches | Préfixe / suffixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | raw_ / _amp | Minuscules | [raw_tline_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/01c12730375c45bbac8c31230292ed49/identification) |
| cibles | pas de préfixe | minuscules | [prefixes_sections](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/81960d16e4bb4c74939583c92729af97/history) |
- **Cadastre Arcopole** : 

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | aopcad. | Minuscules | [aopcad.lieudit](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/a98e5a9e8ae8425e81de8c4a729e9aba/identification) |
| cibles | *ajouter le préfixe* | *ajouter la casse* | *Ajouter un exemple* |
- **ZICO** : En attente du scan du client

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Majuscules | [zico](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/f925aa34e2cd4ef7b995c13d38ea425b/identification)
| cibles | *ajouter le préfixe* | *ajouter la casse* | *Ajouter un exemple* |
- **ZNIEFF continentales** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Minuscules | [znieff1](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/18c047b315654897b0b20938b4d094d0/identification) |
| cibles | Pas de préfixe | Minuscules | [znieff1](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/68dea6f0aa074b8b87c423b7fd956fbe/history) |
- **ZNIEFF maritimes** :

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Minuscules | [ZNIEFF2_MER](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/7aebc96ed5f040c0b9c86ac936505650/identification) |
| cibles | Pas de préfixe | Minuscules | [znieff2_mer](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/61e749d02c8d4441a5ed8325153a514d/history) |
- **ZPS** : 

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Minuscules | [zps1712](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/0ec485b6e259470c8265cf1f4ecada90/identification) |
| cibles | Suffixe | Minuscules | [zps2012](https://scan.isogeo.com/g/4b729516af434ba0b2c816216440a6ad/entrypoints/60f03e4bb3b466499f0c1b50/requests/60f03e4cb3b466499f0c1b51) |
- **ZSC/SIC** : En attente du scan du client

| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | Pas de préfixe | Minuscules | [sic1712](https://app.isogeo.com/groups/4380a3dd30df481aa19c7883e8ddee0d/resources/d0c61d0194cf4bdf9ccad865a7d39448/identification) |
| cibles | Suffixe | Minuscules | [sic2012]() |

## Règles de migration

- Règles communes à toutes les fiches
   - HAROPA PORT – LE HAVRE
   - Contact : point de contact du GT avec le rôle point de contact
- **BD Topo** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | Département des Pyrénées-Atlantiques | HAROPA PORT – LE HAVRE |
| Exemple | Entités de transitions [BD TOPO®] - Département des Pyrénées-Atlantiques | Entités de transitions [BD TOPO®] - HAROPA PORT – LE HAVRE |
- **BD Carto** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | HAROPA PORT – LE HAVRE |
| Exemple | Zones d'habitat [BD CARTO®] - XXXX | Zones d'habitat [BD CARTO®] - HAROPA PORT – LE HAVRE |
- **BD Parcellaire** : **(à mettre à jour)**

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Entités rattachées [ADMIN EXPRESS] - France Métropolitaine | Entités rattachées [ADMIN EXPRESS] - HAROPA PORT – LE HAVRE |
- **Admin Express** :

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Entités rattachées [ADMIN EXPRESS] - France Métropolitaine | Entités rattachées [ADMIN EXPRESS] - HAROPA PORT – LE HAVRE |
- **Route500 et Route 120**

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Entités rattachées [ROUTE 500®] - France Métropolitaine | Entités rattachées [ROUTE 500®] - HAROPA PORT – LE HAVRE |
- **Scan 25, Scan Express** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Fond cartographique historique à l’échelle 1 : 50 000 [Scan 50® Historique] - France Métropolitaine | Fond cartographique historique à l’échelle 1 : 50 000 [Scan 50® Historique] - HAROPA PORT – LE HAVRE |
- **Contours IRIS** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | HAROPA PORT – LE HAVRE |
| Exemple | Contours des îlots regroupés pour l'information statistique [Contours IRIS®] - XXXX | Contours des îlots regroupés pour l'information statistique [Contours IRIS®] - HAROPA PORT – LE HAVRE |
- **RGE Alti** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Modèle numérique de terrain de résolution 5 mètre [REG Alti®] - France Métropolitaine | Modèle numérique de terrain de résolution 5 mètre [REG Alti®] - HAROPA PORT – LE HAVRE |
- **FranceRaster** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Fond cartographique à l’échelle 1 : 8 000 000 [FranceRaster®] - France Métropolitaine | Fond cartographique à l’échelle 1 : 8 000 000 [FranceRaster®] - HAROPA PORT – LE HAVRE |
- **RPG** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | lots anonymes [RPG®] - France Métropolitaine | lots anonymes [RPG®] - HAROPA PORT – LE HAVRE |
- **Cadastre Etalab - Version Complète** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | HAROPA PORT – LE HAVRE |
| Exemple | Objets linéaires divers [Cadastre Etalab®] - XXXX | Objets linéaires divers [Cadastre Etalab®] - HAROPA PORT – LE HAVRE |
- **Cadastre Arcopole** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | HAROPA PORT – LE HAVRE |
| Exemple | Hydrographie (Texte) [Cadastre Arcopole] - XXXX | Hydrographie (Texte) [Cadastre Arcopole] - HAROPA PORT – LE HAVRE |
- **ZICO, ZNIEFF, ZPS et ZSC/SIC** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | France Métropolitaine | HAROPA PORT – LE HAVRE |
| Exemple | Zones naturelles d'intérêt écologique, faunistique et floristique continentales de type 2 [ZNIEFF] - France Métropolitaine | Zones naturelles d'intérêt écologique, faunistique et floristique continentales de type 2 [ZNIEFF] - HAROPA PORT – LE HAVRE |

## Suivi

- [x] **BD alti** : Go !
- [x] **Scan 25** : Go ! 
- [x] **RGE Alti** : Go !
- [x] **FranceRaster** : Go !
- [x] **RPG** : Go !
- [x] **BD Topo 3.0** : Go !
- [x] **Admin Express** : Go !
- [x] **Route500** : Go !
- [x] **Contours IRIS** : Go !
- [x] **ZICO** : Go !
- [x] **ZIEFF** : Go !
- [x]  **ZPS** : Go !
- [x] **ZSC/SIC** : Go !
- [x] **Cadastre Arcopole** : **Ne pas migrer**
- [x] **OCS GE** : **Ne pas migrer**
- [x] **Route120** : En attente de documentation 
- [x] **Scan Express** : En attente de documentation 
- [x] **BD Carto** : Go !
- [x] **BD Parcellaire** : En attente de documentation 
- [x] **Cadastre Etalab Complet** : Go !

**Comment by SimonSAMPERE** [comment]
En attendant que les catalogues cible soient remplis, je mets le ticket en stand-by

**Comment by SimonSAMPERE** [comment]
27 fiches dupliquées aujourd'hui : 
* RGE ALTI
* BD ALTI
* France RASTER
* SCAN 25

**Comment by SimonSAMPERE** [comment]
Le [RPG](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A31b89f63ba9c4b2489b7c1bad7748d4b) a été dupliqué.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C , j'ai généré une [table de correspondance](https://github.com/isogeo/migrations-toolbelt/files/7135763/correspondances_1631178907.csv) pour : 
* BD TOPO
* ADMIN EXPRESSE
* ROUTE500
* CONTOURS IRIS
* ZICO, ZNIEFF...

Est-ce que tu pourrais compléter les 13 premières lignes (celles où "nb_match" est différent de 1). Voici les différent cas de figures : 
* nb_match = 0 : si la fiche cible n'existe pas, tu peux supprimer la ligne, sinon remplis les colonnes "target_name" et "target_uuid"
* nb_match > 1 : plusieurs fiches cibles ont été trouvées, détermine laquelle est la bonne et remplis les colonnes "target_name" et "target_uuid" avec son nom et son uuid

**Comment by Mouzzi-C** [comment]
J'ai mis à jour la table de corresoondance. Voilà [le csv](correspondances_1631178907.csv](https://github.com/isogeo/migrations-toolbelt/files/7137674/correspondances_1631178907.csv)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C pour CONTOURS-IRIS ya toujours 6 fiches de destination, ça veut dire qu'il faut migrer la fiche de référence dans les 6 fiches de destination ?

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C j'ai aussi une autre question : dans la [fiche cible ARRONDISSEMENT](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/7701fdf03481416fb9553e875dadab5e), je dois migrer [ARRONDISSEMENT_MUNICIPAL](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/23a46d3db9a5434fb9632863a026f93d) ou [ARRONDISSEMENT_MUNICIPAL](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/e1b5cdf5fcda4145ba57f842c77b0346) ?

**Comment by Mouzzi-C** [comment]
J'ai pas vu l'erreur de matching pour la donnée [ARRONDISSEMENT](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/7701fdf03481416fb9553e875dadab5e/identification). 
Voilà la table de correspondance modifiée. [correspondances_LeHavre.csv](https://github.com/isogeo/migrations-toolbelt/files/7162098/correspondances_LeHavre.csv)

En ce qui concerne le contours iris, il faut migrer uniquement vers la fiche cible mentionnée dans la table de correspondance.

**Comment by SimonSAMPERE** [comment]
T'inquiète le soucis n'était pas indiqué dans la table pour Arrondissement, je m'en suis aperçu après.

Par contre pour CONTOUR_IRIS ya toujours 6 fiches de destination indiquées dans la table (dans le champs target_uuid) donc je sais toujours pas laquelle des 6 est la cible : 
* https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/1ded79c97597440bb8ebc102add87d51
* https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/e6e8ca3f75394fecacb6f9f046f739d6
* https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/08a2790b7b01408ebb614fb765948cd1
* https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/1636487b2ab54e11ad2945e43141dad9
* https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/6748344c150c472790da8ba10dbabe2e
* https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/c436b5d2a29a466e9ff05e5548eaa286

Et c'est pas obligé d'en choisir une, on peut aussi migrer la source dans les 6 fiches, il faut juste me dire quoi faire.

**Comment by SimonSAMPERE** [comment]
81 fiches migrées aujourd'hui pour : 
* BD Topo 3.0
* Admin Express
* Route500
* Contours IRIS
* ZICO
* ZIEFF
* ZPS
* ZSC/SIC

**Comment by SimonSAMPERE** [comment]
Pour le Cadastre Etalab, j'ai lancé une correspondance mais c'est complexe, je te laisse checker :
[correspondances_CadEtalab.csv](https://github.com/isogeo/migrations-toolbelt/files/7267638/correspondances_CadEtalab.csv)

**Comment by Mouzzi-C** [comment]
Je t'ai mis à jour la table de correspondance. 

Il y plusieurs données pour lesquelles on a pas de correspondances, c'est normal. Tu peux y aller pour la migration. 

Je t'ai aussi ajouté les informations pour la bd carto dans l'issue.

**Comment by Mouzzi-C** [comment]
Yes carrément. Je te dis dès que c'est bon 👍

**Comment by Mouzzi-C** [comment]
tu veux profiter de la dernière phase de la presta pour modifier le territoire ? 

Si oui, il faudra remplacer : 
* HAROPA PORT – LE HAVRE
* par : HAROPA PORT | LE HAVRE

**Comment by SimonSAMPERE** [comment]
Les 7 fiches du Scan Express ont été dupliquée : https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A31cbf5b1caea466e825a5482907a9c5b

**Comment by SimonSAMPERE** [comment]
En attendant de savoir comment gérer le nouveau système des fiches ressource, j'ai ajouté par lot aux fiches cible de la [BD Carto](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ad49b5d1424054eeabbb0a3ddce7de681) et de la [BD Parcellaire](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A192dbf11d574491ba96e6c24d64f52d8) le lien issu de la [fiche ressource](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/9f2748f59973495fadce4b375e20e844/identification) que j'avais créé dans le groupe du client. Pour la BD Parcellaire j'ai dû d'abord ajouter un lien à la fiche ressource car ce lien était manquant (c'est aussi le cas dans le groupe IGN-F, faudrait que tu checks).

**Comment by SimonSAMPERE** [comment]
53 fiches de la BD Carto, de la BD Parcellaire, du Cadastre Etalab et de Route120 ont été migrée.
voici la table de correspondance à compléter pour les 22 fiches restantes :
[correspondances_GPMH.csv](https://github.com/isogeo/migrations-toolbelt/files/7589468/correspondances_GPMH.csv).
Au passage, j'ai l'impression que la table que tu m'as fournie pour le Cadastre Etalab est identique à la version que je t'ai donné à compléter.
