### ISSUE TITLE
[MD_REF] - Reims

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#143]
# Prestation de Métadonnées de Référence - *Reims*

Groupe cible : [aab0084b59d54847a9a65b0cd75194fd](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/dashboard/formats)

Deadline : Dès que tu peux

Contexte : Migration d'un catalogue offerte avec la prestation de migration

### DGFIP (98b00a0db4ab411995ce08f6a47eb8a7)
 
| Catalogue source | Catalogue cible |
| --- | ---- |
| [**Cadastre Etalab - Version complète**(59dfcc70a0514414822919cee96140fc)](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A59dfcc70a0514414822919cee96140fc) | [486da55694e34942b35ce5f3e487d3e4](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A486da55694e34942b35ce5f3e487d3e4) |

## Critères de correspondance
- **Cadastre Etalab - Version Complète** : 

| Fiches | Préfixe / Suffixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | raw_ / _amp | Minuscules | [raw_tline_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/01c12730375c45bbac8c31230292ed49/identification) |
| cibles | cadastre.geo_ | Minuscules | [cadastre.geo_section](https://app.isogeo.com/groups/aab0084b59d54847a9a65b0cd75194fd/resources/ceba2dc464514e13ab0f91086535926c/identification) |

- Critère de correspondance des attributs : Ne pas prendre en compte la casse pour effectuer la correspondance.

## Règles de migration
- Ajouter à toutes les fiches : 
  - le point de contact du GT en "Point de contact"
  - les mots-clés : "pci" et "plan cadastral informatisé"
- **Cadastre Etalab - Version complète** : 

|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | Grand Reims |
| Exemple | Bâtiments [Cadastre Etalab®] - XXXX | Bâtiments [Cadastre Etalab®] - Grand Reims |

## Suivi

- [x] **Cadastre Etalab - Version complète** : Donnée scannée - Go!
- [x] Documentation manuelle des attributs pour lesquelles une correspondance n'est pas établie - à faire par le chef de projet

**Comment by SimonSAMPERE** [comment]
Voici la [table de correspondance](https://github.com/isogeo/migrations-toolbelt/files/7209978/correspondances_cadEtalab_reims.csv), il manque 3 correspondances :
* [raw_subdsect_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/7d4e63faaff04468967434274cace86f)
* [raw_boulon_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/8c5d68a45d8d4f189a86ad56eba2d3ce)
* [raw_charge_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/74bd182862184182bbf9268513b080bb)

**Comment by Mouzzi-C** [comment]
Les trois fiches restantes n'ont pas de correspondances donc tu peux lancer la migration 🦺 👍

**Comment by SimonSAMPERE** [comment]
Les 18 fiches ont été migrées.
