### ISSUE TITLE
Remplacement des liens de ressources des fiches de l'IGN

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#148]
## Contexte
Depuis la mise à jour de la plateforme de l'IGN, tous les liens de spécifications et ressources ne sont plus valides. Il faut donc les modifier ou, dans certains cas, les supprimer.

Les liens des spécifications ont été modifiés manuellement. Il reste à modifier les liens ressources.

## GT IGN [504f49055abc4d0b9865038fbc99b44b](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/dashboard/formats)

Il faudra supprimer les ressources de types liens suivantes :

| Nom de la ressource source | Nom de la ressource cible |
| ---------------------- | --------------------- |
| Documentation - BD TOPO® 3.0 |           Pas de ressource cible          |
|          Métadonnées de produit - BD TOPO® 3.0          |           Métadonnées de produit - BD TOPO® 3.0          |
|          Métadonnées de produit - ADMIN EXPRESS          |           Métadonnées de produit - ADMIN EXPRESS 3.0          |
|          Métadonnées de produit - BD ALTI®           |           Métadonnées de produit - BD ALTI® 2.0          |
|          Métadonnées de produit - BD CARTO®            |           Métadonnées de produit - BD CARTO® 4.0          |
|          Métadonnées de produit - BD ORTHO®            |          Métadonnées de produit - BD ORTHO® 2.0           |
|          Métadonnées de produit - Contours... IRIS® 2.1            |            Métadonnées de produit - CONTOURS... IRIS® 2.1        |
|          Métadonnées de produit - RGE ALTI®            |          Métadonnées de produit - RGE ALTI® 2.0           |
|          ROUTE 500® - Métadonnées de produit           |           Métadonnées de produit - ROUTE 500® 3.0          |
|          Métadonnées de produit - RPG            |          Métadonnées de produit - RPG 2.0           |
|          Téléchargement - RPG            |          Pas de ressource cible           |
|          Métadonnées de produit - Scan 1000®            |          Métadonnées de produit - SCAN 1000® 2.1           |
|          Métadonnées de produit - Scan 100®            |          Métadonnées de produit - SCAN 100® 2.0           |
|          Métadonnées de produit - Scan 25®            |           Métadonnées de produit - Scan 25® 3.1          |

Il faudra aussi supprimer ce lien de téléchargement des fiches ROUTE 500

| Nom de la ressource | URL de la ressource |
| ---- | ---- |
|          Route 500® édition 201 - Téléchargement            |           ftp://ROUTE_500_ext:UqueemievaiDah3k@ftp3.ign.fr/ROUTE500_3-0__SHP_LAMB93_FXX_2020-08-04.7z.001         |

Une fois les ressources remplacées, il faudra ajouter la ressources liée à la donnée en question depuis cette fiche ressource : 
[feb162db72374825a6f4375ed2850556](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/feb162db72374825a6f4375ed2850556/resources)

## Même chose pour 4 autres groupes

Pour les 4 GT, il faudra : 
1. Dupliquer la fiche ressource : [feb162db72374825a6f4375ed2850556](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/feb162db72374825a6f4375ed2850556/resources)
2. Faire la même chose que pour le GT de l'IGN (avec la suppression du lien de téléchargement des route 500)

Liste des GT à nettoyer : 
* GPM du Havre : [4b729516af434ba0b2c816216440a6ad](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/dashboard/formats)
* Marseille : [e3a3412cae2843c997862f9d18857dfc](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/dashboard/formats)
* MRN : [80e2a30f471e43f1845a33d98e6a42e3](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/dashboard/formats)
* CD 45 : [4baf1fbdf4234d91b52c56978a292938](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/dashboard/formats)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C , si tu as mis "Route 500® édition 201 - Téléchargement" c'est parce que c'est la seul qu'il faut juste supprimer sans la remplacer par un des liens de la fiche ressource c'est bien ça ?

**Comment by Mouzzi-C** [comment]
Yes c'est bien ça 👍

**Comment by SimonSAMPERE** [comment]
La [fiche ressource de IGN-F](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/feb162db72374825a6f4375ed2850556/resources) a été dupliquée, dans les GT suivants : 
* GPM du Havre : [bceb8bdefda94cc1856d3a236e36cadc](https://app.isogeo.com/groups/4b729516af434ba0b2c816216440a6ad/resources/bceb8bdefda94cc1856d3a236e36cadc/resources)
* MAMP : [859ed6e5f7fc4fd49a5c589aafc58292](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/859ed6e5f7fc4fd49a5c589aafc58292/resources)
* MRN : [fef80a89e62242cf815e4078b425a722](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/resources/fef80a89e62242cf815e4078b425a722/resources)
* CD 45 : [5c02e033f5504666896b0ad6c5ab1cff](https://app.isogeo.com/groups/4baf1fbdf4234d91b52c56978a292938/resources/5c02e033f5504666896b0ad6c5ab1cff/resources)

**Comment by SimonSAMPERE** [comment]
J'ai bien avancé sur le script de création des nouveaux liens, je le lancerai lundi sur le groupe IGN-F. Le même jour, j'essaierai de faire le script de suppression des anciens liens et de l'exécuter. Si on est content du résultat je lancerai les scripts sur les groupes des clients.

**Comment by SimonSAMPERE** [comment]
J'ai lancé les deux scripts (suppression des anciens liens et ajout des nouveaux) sur les fiches de IGN-F. @Mouzzi-C je te laisse checker ça et me faire un retour avant que je lance les scripts sur les groupes de clients.

**Comment by Mouzzi-C** [comment]
J'ai fait le tour des catalogues, voilà le résultat : 
* BD Topo → pas de ressource
* BD Ortho → pas de ressource pour une des trois fiches. Je l'ai ajoutée à la main
* Route 500 → 2 ressources non supprimées sur 3 (dans toutes les fiches)

**Comment by SimonSAMPERE** [comment]
Pour la BD Topo je pense que c'est mon script de suppression qui a supprimer tous les liens comme un connard vu que les anciens et les nouveaux ont le même nom. Il faut que je trouve comment gérer ça, c'est bien [celui-ci](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A54eb129b4dd840ada8de710994a310dc) le catalogue concerné ? 

Pour BD Ortho et Route 500, est-ce-que c'est possible que les liens concernés aient eu un titre légèrement différent de ce qui est indiqué dans le ticket (genre un accent, une majuscule ou un espace) ?

**Comment by Mouzzi-C** [comment]
Yes, c'est bien ce catalogue là pour la BD Topo. 

Pour la bd ortho ça à fonctionné pour les 2 autres fiches donc je me dis que non. J'ai revérifié pour les route 500 et en principe les titres sont bons aussi.

**Comment by SimonSAMPERE** [comment]
Ok si ça te va je m'y remets jeudi

**Comment by SimonSAMPERE** [comment]
* BD Ortho --> voici la [fiche concernée](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/c2f9534deff7424c97185b7768ee1dcd/identification), il faudra la vérifier lorsque les scripts auront été lancés sur les groupes de travail des clients
* BD Topo --> les nouveaux liens ont été supprimés car ils avaient le même nom que les anciens qui devaient être supprimés, j'ai modifié le script de suppression pour ne pas supprimer les liens de type "link", il faut encore que je vérifie que ça fonctionne, en attendant j'ai ajouté le lien qui avait été supprimé par lot
* Route 500 --> la première ressource non supprimée (de type "url" avec actions = ['download']) je sais pas pourquoi elle ets pa ssupprimée faut que je check ; la deuxième ressource c'est une ressource de type link issue d'une fiche ressource propre à Route 500 qu'on a supprimé ce qui a eu pour conséquence de supprimer tous les liens dans les autres fiches

Au passage on a découvert qu'on pouvait associer à une fiche d'un groupe A, le lien issu d'une fiche Ressource d'un groupe B et que mettre à jour le lien de la fiche ressource du groupe B mettait bien à jour le lien de la fiche du groupe A

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C  j'ai lancé les scripts sur les groupes des clients, je te laisse checker.

**Comment by Mouzzi-C** [comment]
C'est tout bon. Bien joué man !

**Comment by Mouzzi-C** [comment]
Finalement, je réouvre l'issue ! 🥳 

Un comportement inattendu a été remonté par Marseille. Les liens de ressources associés aux fiches de métadonnées ne sont pas visibles pour eux. 

Pour qu'un utilisateur puisse voir une ressource d'un autre GT, il faut que cette utilisateur ait accès aux deux GT (le GT cible et source de la ressource).

**Comment by SimonSAMPERE** [comment]
Ok je suis anéanti mais qu'à cela ne tienne, _the show must go on_.

Je vais donc procéder de la manière suivante : 
* re-dupliquer la fiche ressource du groupe de l'IGN dans les 4 groupes de travail concernés
* faire un nouveau script pour corriger les liens créés afin de remplacer les liens de la fiche ressource de l'IGN par ceux des fiches dupliquées

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C a priori c'est bon c'est réglé ! THE SHOW WENT ON
