### ISSUE TITLE
possible vulnerability in your isogeo server web service

### ISSUE THREAD

**Issue by psytester** [isogeo/migrations-toolbelt#174]
Hello IsoGeo team,

I found a vulnerability in your web service and I use this unusual way as issue in github to get in contact with you, because

I wrote you an e-mail, but this was blocked by your mail server as possible spam.
I wrote you at twitter @isogeo without any reaction
I wrote CERT France to get in contact with you without any first feedback from there

Once again, how can we get together that I can send you my findings?

**Comment by jgrosmaire** [comment]
We were contacted by CERT-FR and are working on fixing the issue.
