### ISSUE TITLE
Métadonnées de référence Marseille

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/migrations-toolbelt#24]
Cette prestation consiste à effectuer 8 migrations depuis différents groupe de travail administrés par Isogeo vers le [groupe de travail de l'AMP](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/inventory/search?p=1&ob=%23relevance&od=des) :

* **Vecteurs :**

  * **Cadastre Geomap :** *stand-by du chef de projet*

    - [x] dupliquer les fiches du catalogue DGFIP_Cadastre du groupe de Marseille dans le catalogue _Duplicated du groupe DGFIP
    - [x] migrer les fiches du catalogue GEOMAP_IMAGIS dans celles du catalogue _Duplicated au sein du groupe DGFIP
    - [x] migrer les fiches du catalogue _Duplicated du groupe DGFIP dans le catalogue DGFIP_Cadastre du groupe de Marseille

  * **BD Topo 3 :**

    - [x] créer la table de correspondance

    - [x] relancer le script de documentation des attributs récurrents

    - [x] réaliser la migration : partir du script de migration de Lorient et rajouter les [règles spécifiques](https://docs.google.com/document/d/1pLee7kJnL2qIn_uFBtqdBSbbn-rGD_W4GzWw8HE4EdQ/edit#heading=h.a0rqb4eni1nf)  + compliquations

  * **Cadastre Etalab :** *en stand-by du scan chez le client*

  * **Contours IRIS :** *en stand-by du scan chez le client*

* **Rasters**

  - [x] **FranceRaster :**

  - [x] **BD Alti :**

  - [x] **BD Ortho :**

  - [x] **Scan 25 :**

**Comment by Mouzzi-C** [comment]
Il y a finalement le cadastre Etalab à migrer. 

## Catalogues
* Source : [59dfcc70a0514414822919cee96140fc](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/inventory/search?p=1&ob=title&od=asc&q=catalog%3A59dfcc70a0514414822919cee96140fc)
* Cible : [ef299df6941e4c89b7b1a1fbd1e808b8](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/inventory/search?p=1&ob=title&od=asc&q=catalog%3Aef299df6941e4c89b7b1a1fbd1e808b8)

## Critère de correspondance
| Fiches | Préfixe | Casse | Exemple |
| --- | --- | ---- | --- |
| Sources | raw_ | Minuscules | [raw_batiment_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/28775cfa185b4741a4870b97de4b4ae8/identification) |
| Cibles | cad.cad_edigeo_etalab_ | Minuscules | [cad.cad_edigeo_etalab_batiment_amp](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/eed7ba50b8f842de8c57cb1aac11a653/identification) |

## Règles de migration 
* Ajouter les mots-clés AMP et référentiels à toutes les fiches
* Ajouter le contact "Métropole Aix-Marseille Provence" en point de contact pour toutes les fiches
* Modifier le titre de la manière suivante : 
|  | Fiche source | Fiche cible |
|--- | --- | --- |
| Remplacer | XXXX | Métropole Aix-Marseille Provence |
| Exemple | Bâtiments [Cadastre Etalab®] - XXXX | Bâtiments [Cadastre Etalab®] - Métropole Aix-Marseille Provence |

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, sur les 20 fiches cible, j'ai réussit à établir 18 correspondances automatiques. COncernant les 2 fiches restante : 
* [cad.cad_edigeo_etalab_lieudit_amp](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/8dda2c787dfb45929fb8727630f9edc2/identification) --> j'ai réussit à établir la correspondance manuellement avec [raw_lieu_dit_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/ee9f8241b08a410786393c947599419c/identification)
* [cad.cad_edigeo_etalab_etiq_amp](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/7f47941a4cc14679a0c6c1e97ff27280/identification) --> je n'ai pas réussit à établir la correspondance manuellement

**Comment by Mouzzi-C** [comment]
Je m'occupe de la dernière fiche. Tu peux migrer le reste 👍 

Pour les deux fiches qui n'ont pas de correspondance, je poserai la question quand on livrera le reste mais je pense qu'il ne les utilisent pas vu qu'ils ne les ont pas mis dans leur BD.

**Comment by SimonSAMPERE** [comment]
Ok super j'essaye de m'en occuper ce matin.

**Comment by Mouzzi-C** [comment]
Les deux fiches restantes sont scannées
|Fiche cible | Fiche source |
|:---:|:----:|
| [cad.cad_edigeo_etalab_tronfluv_amp](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/791c347faa034206af6b0cec1ae9163f/identification) | [raw_tronfluv_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/3aca5b9f5f8f4b11b7f73ececf68bc9f/identification) |
| [cad.cad_edigeo_etalab_tronroute_amp](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/resources/23f38a0ade2a46dba5d75f499d19c672/identification) | [raw_tronroute_amp](https://app.isogeo.com/groups/98b00a0db4ab411995ce08f6a47eb8a7/resources/eff3fdb6aea445908c7aa47e95e64dcc/identification) |

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C , c'est bon c'est fait !
