### ISSUE TITLE
Migration Mayenne

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#29]
Nous devons réaliser une migration pour le département de la Mayenne (depuis mi-2019 déjà...)

**Ressources**

- [Dossier drive](https://drive.google.com/drive/folders/1nKmASZeGSyxrgBlvUDrwPyEMb0gItDsw)
- [Document de travail](https://docs.google.com/document/d/1qEfWzW3aP9sEzFFmpYpv1NeJCtv8E59bRExeUBgV248/edit#)
- Groupe de travail concerné : [0a85f99cd4eb43239debf974e33f4d26](https://app.isogeo.com/groups/0a85f99cd4eb43239debf974e33f4d26/inventory/search?p=1&ob=%23relevance&od=des)
- Catalogue M_Source : [37380c717301498a998e88d3a5d03468](https://app.isogeo.com/groups/0a85f99cd4eb43239debf974e33f4d26/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A37380c717301498a998e88d3a5d03468)
- Catalogue M_Cible : [e5c8c6d6374543ff8218bf3dcfcb5c6e](https://app.isogeo.com/groups/0a85f99cd4eb43239debf974e33f4d26/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ae5c8c6d6374543ff8218bf3dcfcb5c6e)

**Principales étapes**

- [x] Générer la table de correspondance
  - [x] [Conseil départemental de la Mayenne Interne](https://app.isogeo.com/groups/0a85f99cd4eb43239debf974e33f4d26/dashboard/formats)
  - [x] [Département de la Mayenne](https://app.isogeo.com/groups/d006f78cd4134ee2a3677cde15c72450/dashboard/formats) 
  - [x] Les autres groupes de travail
- [x] Migrer les fiches : 
  - [x] [Conseil départemental de la Mayenne Interne](https://app.isogeo.com/groups/0a85f99cd4eb43239debf974e33f4d26/dashboard/formats)
  - [x] [Département de la Mayenne](https://app.isogeo.com/groups/d006f78cd4134ee2a3677cde15c72450/dashboard/formats) 
  - [x] Les autres groupes de travail
- [x] Supprimer les fiches Source: 
  - [x] [Conseil départemental de la Mayenne Interne](https://app.isogeo.com/groups/0a85f99cd4eb43239debf974e33f4d26/dashboard/formats)
  - [x] [Département de la Mayenne](https://app.isogeo.com/groups/d006f78cd4134ee2a3677cde15c72450/dashboard/formats) 
  - [x] Les autres groupes de travail

**Particularité**

Certaines fiches sont associées à des couches de services via l'ancienne méthode qui n'implique pas de fiche de service ([exemple](https://app.isogeo.com/groups/d006f78cd4134ee2a3677cde15c72450/resources/c455e9fd74484d3288f79f70d4df8267/resources)). Il faut donc récupérer cette information (onglet "Ressources") puis, au choix : 
* associer la fiche cible de la même manière
* créer les fiches de service et associer les fiches cible de la manière actuelle

**Comment by SimonSAMPERE** [comment]
Concernant la particularité des couches de services associées via l'"ancienne méthode" : il s'avère que ces association prenne la forme d'un lien (rubrique "Services cartographiques" de l'onglet "Ressources"), renvoyé par l'API de la même manière qu'un lien de téléchargement (rubrique "Données" de l'onglet "Ressources") ou qu'un lien "traditionnel" (rubrique "Liens" de l'onglet "Ressources"). Étant donné que le **Duplicator** gère l'import des liens dans les fiches cibles, ces associations de couches de services sont recréées au même titre que les liens de téléchargement ou liens "traditionnel" dans la fiche cible. Aucune modification n'a donc dû être apportée aux scripts de migration pour gérer cette particularité.
