### ISSUE TITLE
Rouen - réassocier les couches de services géographiques

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/migrations-toolbelt#38]
Le groupe de travail de Rouen ([80e2a30f471e43f1845a33d98e6a42e3](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/dashboard/formats)) a créé 2 fiches de service ESRI dont certaines couches avait été associées à des fiches de métadonnées avant la semi-résolution du [bug lié aux formats ESRI](https://github.com/isogeo/isogeo-database-central/issues/6).
Les fiches de service concernées sont les suivantes :
* [2e709eeb72884daf97a07ec927111978](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/resources/2e709eeb72884daf97a07ec927111978/identification)
* [3ca708da46dc4fe8ba23f0a05e36ab15](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/resources/3ca708da46dc4fe8ba23f0a05e36ab15/identification)

1. Créer un script qui prend en entrée des ids de fiches de service et génère un fichier csv contenant une ligne par association d'une couche du service à une fiche de métadonnées. Chaque ligne comprendra : 
    * le titre de la fiche de service
    * l'id et le titre de la couche du service
    * l'id, le nom et le titre de la fiche de métadonnées Isogeo qui lui a été associé.

    --> le fichier a été généré et se trouve [ici](https://drive.google.com/drive/folders/1rB_y5V4-pIHpO55s9fwVEuzZurjC2_D-)

2. Supprimer puis recréer manuellement les fiches de services dans app [en important le JSON](http://help.isogeo.com/admin/fr/features/inventory/md_services/srv_howto.html#srv_auto_private).

3. Créer un script qui prend en entrée l'id des nouvelles fiches de service et le fichier csv créé par le premier script pour recréer les associations couche-fiche.

**Comment by leodarengosse** [comment]
Les nouvelles fiches de services ont été créée

- [Référentiels ](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/resources/bcaba8265beb45df9cbf20cdcf54c753/identification)
- [Métiers](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/resources/9b42f23690b549018d8eb333eb488866/resources)
