### ISSUE TITLE
Migration Caen la Mer

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#50]
Groupe concerné : [9f00efda06da49608709e94379218d27](https://app.isogeo.com/groups/9f00efda06da49608709e94379218d27/inventory/search?p=1&ob=%23relevance&od=des)

**Etapes** 

1. Détecter les doublons
2. Etablir une table de correspondance
3. Migrer les fiches

**Comment by SimonSAMPERE** [comment]
Un script d'identification des doublon a été lancé pour récupérer les UUID de toutes les fiches qui ont le même nom de donnée.
* il y a deux cas de "triplons" (trois fiches qui ont le même nom de donnée) --> trouver la cible et supprimer les autres si elle sont vides ou trouver la source si c'est pas le cas
* il y a 107 cas de doublons : 107 nom de donnée auxquelles deux fiches correspondent --> le script à distingué la fiche source de la fiche cible en se basant sur la date de création de la fiche --> à valider 
* il y a 532 absences de doublons --> rien à faire

**Comment by SimonSAMPERE** [comment]
Le fichier `mapping_caen_la_mer.csv` stocké dans google drive (G:\Mon Drive\Racine Isogeo\Clients\86_CAEN-LA-MER\03_REALISATION\04_CATALOGAGE\Migration_doublon) a été généré par un nouveau script de mapping plus élaboré.
La distinction entre source et cible repose sur les critères conjugués de la date de création de la fiche et de la date de dernière modification --> si une des deux fiches a été créée ET modifiée pour la dernière fois avant l'autre, alors elle est considérée comme la source.

**Récapitulatif :**
* toujours 2 cas de "triplons" : a priori, dans les deux cas, aucune des fiches n'est plus documentée que les autres, il suffit donc de trouver celle qui est recensée par le scan et supprimer les 2 autres
* toujours 107 cas de doublons : 
  * dont 88 pour lesquels la distinction entre source et cible n'a pas posé de problème --> vérifier sur un échantillon de 10 fiches que la cible est bien recensée par le scan
  * dont 19 pour lesquels la distinction entre source et cible n'a pu être établie sur le critère présenté plus haut --> regarder avec le chef de projet
* toujours 532 absences de doublon

**Comment by SimonSAMPERE** [comment]
Le script de migration a été exécuté le 20/10/2020. Je propose que l'équipe projet envoie un mail de récap au client avant de supprimer les fiches sources. 

Voilà quelques éléments pour remplir ce mail : 

- 109 cas de doublons ou triplons on été identifiés : c'est-à-dire que 107 des données scannées correspondaient à plus d'une fiche de métadonnées dans l'inventaire. L'objectif de la migration été de faire en sorte qu'il ne reste plus qu'une fiche de métadonnées par donnée. L'enjeu été double : 
  - faire en sorte que la fiche restante (fiche cible) soit celle qui est référencée par le scan et donc celle qui continuera à être mise à jour
  - récupérer les informations contenues dans les fiches non-référencées (fiche source) par le scan avant de les supprimer

- sur ces 109 cas de doublons/triplons : 
  - 2 cas de triplons : 3 fiches de métadonnées correspondant à la même donnée --> dans chaque cas, la fiche référencée par le scan a été identifiée et les autres, qui ne contenaient aucune information supplémentaire ont été supprimées
  - 107 cas de doublons : 
    - 56 ont été traités via un script de migration automatique : les informations figurant dans la fiche source (non-référencée par le scan) ont été réécrites dans la fiche cible (référencée par le scan) --> il reste à supprimer les fiches sources après validation du client
    - 50 ont été traitées manuellement par notre équipe : la fiche source a été supprimée directement si elle ne comportait aucune information supplémentaire
