### ISSUE TITLE
[MD REF] - Rouen 

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#56]
# Prestation de Métadonnées de Référence - Rouen

Groupe cible : [80e2a30f471e43f1845a33d98e6a42e3](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/dashboard/formats)

Deadline : Pas de deadline

Contexte : Il s'agit d'une prestation de migration de métadonnées de référence pour la Métropole Rouen Normandie.

## Catalogues à migrer

* BD Topo 3.0 : [54eb129b4dd840ada8de710994a310dc](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A54eb129b4dd840ada8de710994a310dc)
* BD Carto 4.0 : [64571133cc4148baaad15c400e255fb4](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A64571133cc4148baaad15c400e255fb4)
* Admin Express : [7dd4fd6da07f403ba4419390f3815362](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A7dd4fd6da07f403ba4419390f3815362)
* Route 500 : [0bd42e9d5a724704ab17127168262a85](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A0bd42e9d5a724704ab17127168262a85)

## Critères de correspondance

- **Commun à tous les catalogues** : 
- **BD Topo 3.0** : les données sont préfixées par la chaine de caractère DONREF.BDT_ (exemple : DONREF.BDT_LIEU_DIT_NON_HABITE)
- **Admin Express** : 
  - le nom de la donnée de la fiche cible est en minuscule
  - le nom de la donnée de la fiche cible est préfixé par la chaine de caractère DONREF.adm_exp_
  - exemple : EPCI --> adm_exp_epci
- **BD Carto 4.0** : Dupliquer les fiches dans le GT du client
- **Route500** :  Les fiches sources et cibles ont le même nom. Ex : COMMUNICATION_RESTREINTE

## Règles de migration

- **Commun à tous les catalogues** : ne pas importer les événements
- **BD Topo 3.0** : 
  - Dans le titre, remplacer "Département des Pyrénées-Atlantiques" par "Haute-Normandie"
- **Admin Express** : 
- **BD Carto 4.0** :
  - Migrer les fiches dans ce catalogue : [648a11f99b814184bc7eb391f0a25250](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/admin/catalogs/648a11f99b814184bc7eb391f0a25250)
  - Dans le titre, remplacer "XXXX" par "Haute-Normandie" 
  - Ne pas migrer les emprises
- **Route500** : Pas de règle particulière

## Suivi

- [x] **BD Topo 3.0** : livré
- [x] **Admin Express** :  migration effectuée conformément à cette [table de correspondance](https://docs.google.com/spreadsheets/d/1WNFqIHy2aFBIcf6vk1bujm0dZXdvVSfrvGIIKXfcHiU/edit#gid=0) Vérification effectuée. Tout est OK. 
- [x] **BD Carto 4.0** : duplication effectuée --> Validée par le chef de projet --> skip la validation du client 
- [x] **Route500** : migration effectuée conformément à cette [table de correspondance](https://docs.google.com/spreadsheets/d/1-6ergZmtTCIsemGgmkTPcR6y6we1B_4xEbQxr8YyV2o/edit#gid=0) --> Validée par le chef de projet --> En attente de la validation du client

**Comment by SimonSAMPERE** [comment]
Quels sont les catalogues à migrer ? depuis quels groupes de travail ?

**Comment by Mouzzi-C** [comment]
Les catalogues concernés sont les suivants :

* BD Topo 3.0 : [54eb129b4dd840ada8de710994a310dc](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A54eb129b4dd840ada8de710994a310dc)
* BD Carto 3.2 : [3f518621e6de4bda9eafb03a9ab27e60](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A3f518621e6de4bda9eafb03a9ab27e60)
* Admin Express : [7dd4fd6da07f403ba4419390f3815362](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A7dd4fd6da07f403ba4419390f3815362)
* Route 500 : [0bd42e9d5a724704ab17127168262a85](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A0bd42e9d5a724704ab17127168262a85)


Le groupe de travail concerné est celui d l'IGN [504f49055abc4d0b9865038fbc99b44b](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des)


En ce qui concerne les champs de métadonnées, je te tiens vite au courant.

**Comment by leodarengosse** [comment]
Pour Admin Express, les données sont préfixées par la chaine de caractère **DONREF.adm_exp_**   (exemple  : adm_exp_epci)

Pour BD Top V3, les données sont préfixées par la chaine de caractère **DONREF.BDT_** (exemple : DONREF.BDT_LIEU_DIT_NON_HABITE)

**Comment by SimonSAMPERE** [comment]
La BD topo 3 a été "livrée".
Maintenant que les BD Carto 3.2, Admin Express et Route 500 ont été documentés côtè Isogeo, on attend le scan du client.

**Comment by Mouzzi-C** [comment]
Admin express est prêt à être migré dans ce catalogue : [de3aaac54cfc42e48b758b4f0c62e10b](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Ade3aaac54cfc42e48b758b4f0c62e10b)

La route500 et la BD Carto ne sont toujours pas scannés.

**Comment by SimonSAMPERE** [comment]
Table de correspondance générée pour Admin Express (8 fiches source) : 
- 5 matchs
- 3 no matchs dont : 
  - 2 matchs impossible car la fiche source n'a pas de nom
  - 1 fiche source nommée qui n'a matché avec aucune cible

**Comment by Mouzzi-C** [comment]
Pas de règle de migration pour l'Admin Express. Pas besoin de migrer les événements.

**Comment by SimonSAMPERE** [comment]
Le script de migration a été lancé pour Admin Express

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, est-ce-qu'on peut considérer qu'on est OK avec Admin Express et cocher la case ?

**Comment by Mouzzi-C** [comment]
Je n'ai pas eu de réponse du client mais ça m'a l'air tout bon donc je vais cocher la case

**Comment by Mouzzi-C** [comment]
Tu peux y aller pour les Route 500 !!

La BD Carto n'est toujours pas scannée. J'attends leur réponse pour savoir s'il la veulent toujours.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, est-ce-qu'on a du nouveau concernant :
* la validation de Route 500 ?
* la migration de la BD Carto ?

**Comment by Mouzzi-C** [comment]
Pour la Route 500 c'est ok. Emma vérifie la bd carto en ce moment, je pense qu'on pourra la migrer d'ici la fin de semaine.

**Comment by Mouzzi-C** [comment]
Mail envoyé au client pour la bd carto. Fin de prestation.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C c'est bon c'est migré, je te laisse vérifier et ré-ouvrir le ticket si nécessaire.

**Comment by Mouzzi-C** [comment]
C'est bon de manière générale. Je met juste un commentaire au sujet d'un comportement observé.

Certains attributs n'ont pas été migrés automatiquement. C'est le cas pour DATE_APP, DATE_CONF et DATE_CREATE pour lesquels le Scan avait récupéré les alias d'attributs. 

J'ai ajouté les infos à la main donc pas besoin de rouvrir l'issue.
