### ISSUE TITLE
Migration [CA Belfort]

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#63]
# Prestation de Migration - *CA Belfort*

Groupe cible : [d9224c1ee4184addaaac8b1aa0091278](https://app.isogeo.com/groups/d9224c1ee4184addaaac8b1aa0091278/inventory/search?p=1&ob=%23relevance&od=des)

Deadline : 

Contexte : Reprendre la migration de Belfort effectuée partiellement en janvier 2019 selon ce [document de travail ](https://docs.google.com/document/d/1U7C86LHNna9M0w8rDroWwXCTPgalk4fpCuCjIRJE8lM/edit)

## Catalogues

- [x] les catalogues Source et Cible existent:
  * Source : [85cd7541a15942a284c5392800aa5230](https://app.isogeo.com/groups/d9224c1ee4184addaaac8b1aa0091278/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A85cd7541a15942a284c5392800aa5230)
  * Cible : [597d2b6970ef409ea7d1707ad380b895](https://app.isogeo.com/groups/d9224c1ee4184addaaac8b1aa0091278/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A597d2b6970ef409ea7d1707ad380b895)
  * M_Migrated : [cc181332fd904488879b6b21f5627221](https://app.isogeo.com/groups/d9224c1ee4184addaaac8b1aa0091278/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Acc181332fd904488879b6b21f5627221) --> à créer

## Critères de correspondance

Table de correspondance manuelle.

## Règles de migration (si nécessaire)

RAS

## Suivi

- [x] table de correspondance : complétée par le client
- [x] migration : fait
- [x] suppression des fiches source : Fiches validée par le client. Go! Go! Go!

**Comment by SimonSAMPERE** [comment]
Il faut corriger [ce fichier](https://docs.google.com/spreadsheets/d/1ZVpPzI0nXhy205954qNKNWbcGsu2Ck8YoUMcv9YE4Fs/edit#gid=501524870)

**Comment by SimonSAMPERE** [comment]
Après un test de récupération des UUID à partir des noms indiqués dans le fichier mentionné ci-dessus : 64 correspondances pour 114 fiches source.

**Comment by Mouzzi-C** [comment]
La [table de correspondance](https://docs.google.com/spreadsheets/d/12VgYN-_SwXgxl7XgjSg38gswphrKHuB8/edit#gid=1942275258) est à jour. Le client l'a complétée. 

Les fiches pour lesquelles il n'y a pas de correspondance ne sont pas à migrer.

**Comment by Mouzzi-C** [comment]
Après échange avec le client : 

Les données restantes préfixées festivites.FIMU_ ne seront pas migrées. Ceci règle le souci des deux fiches cibles qui ont deux fiches sources. 

Il faut aussi garder les fiches cibles documentées.

Il reste donc 3 données, sur les 18 complétés par le client, à migrer : 
* divers.DSU_FIBRE_CAM - sera scannée prochainement
* divers.DSU_PERI_ANTI_MENDICITE - sera scannée prochainement
* reseau.RES_HD_PROJET_GFU - [7da4fcf2a0924e9894ab83a76f1d8296](https://app.isogeo.com/groups/d9224c1ee4184addaaac8b1aa0091278/resources/7da4fcf2a0924e9894ab83a76f1d8296/contacts)

Toutes ces informations sont aussi dans [cette table](https://docs.google.com/spreadsheets/d/1-nBZPLaqbOU0wZuU3q4jPSHxH11qjyPx/edit?rtpof=true#gid=1233845552)

**Comment by SimonSAMPERE** [comment]
J'ai mis à jour la table de correspondances pour garder uniquement les lignes correspondant aux métadonnées à migrer. Je me tiens prêt à la compléter avec les UUID des deux fiches cible manquantes ("sera scannée prochainement").

Parallèlement, j'ai lancé un script pour détecter les fiches cible qui aurait été documentées (celles dont le nom est différent du titre ou qui contiennent un résumé). J'en ai trouvé une cinquantaine. Sur les 68 fiches à migrer ça fait beaucoup. Il faudrait se pencher sur la question pour savoir si on prend le risque d'écraser les information contenues dans les fiches cible déjà documentées.
[Cette table](https://docs.google.com/spreadsheets/d/1e5OsdBPa6tVdWxegcjz3DVgH1Gvu2Czwnkp-T2DjabU/edit#gid=0) contient la liste des uuid des fiches cible en question ainsi qu'un lien vers la fiche dans app.

**Comment by Mouzzi-C** [comment]
J'ai vérifié les différentes fiches de la [table de fiches cibles déjà documentées](https://docs.google.com/spreadsheets/d/1012gpBcUy67QvDhbwSvZdxXsQYaDQopt/edit#gid=1837806458). 

Toutes les fiches étaient déjà migrées donc pas besoin de les remigrer.

**Comment by Mouzzi-C** [comment]
Mail bilan envoyé au client. En attente de réponse.

**Comment by SimonSAMPERE** [comment]
Supprimer les 67 fiches source migrées conformément au tableau de Bilan.

**Comment by SimonSAMPERE** [comment]
Les 67 fiches source ont été supprimées
