### ISSUE TITLE
Créer un script de correction de la description des évènement

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/migrations-toolbelt#64]
**liste des UUID des groupes concernés :** 542bc1e743f6464fb471dc48f0da02d2;59fc5a0b6d6b4fc29c54b482b0e58dfb;d9224c1ee4184addaaac8b1aa0091278;977291192f0f42db91dc3cfc459c3255;3af5511034fb4fe7ac892308f017d2c9;647b3f38f5f442c5b90c6c66261e6ffd;53b3ee084b71407fad63684a53e28579;63b04104f3b0470c966b69d15fbdd06c;4baf1fbdf4234d91b52c56978a292938;aab0084b59d54847a9a65b0cd75194fd;506dd4467e2c40c3abd8715a172eddee;fca78bef7bea4053aa6290cb51084119;32af72140afe4b93b7ce4ca4b7de8df8;6765a5c3fc6f4a4cad2557cbd87f011e;ce896abf83744611910ec52f8d235ab6;c18ddc43d1c045fc85c2ba1b4233eef1;3dc29ce36d9d4b969a08e8669301c751;b9d91170a7a145a884ef762c4f185641;8641752a6d174f13890cdb7686fecb48;7473f15d3be346a3a14396afc41031ab;ff759c1a7a4940c48d7df62e4c0490dc;a95445cf85144fe1bf76f0ef145b13bb;f71fd5294d454482aa42fe143556c503;4b729516af434ba0b2c816216440a6ad;556634ef35a541e7bdb15ba681a4570e;9d29b7ec6d854f7580bb3eb5107dcad1;0c36eef4b81d4f1ca2db0465721feb73;e7d5f7b92a3a4448a5aaafe7676392b2;80e2a30f471e43f1845a33d98e6a42e3;cb2de20aa7834b94b4518c11d1d3d842;9f00efda06da49608709e94379218d27;51e8a14a3bd94e79b57b166e142377b0;6325d0c753214e84b850f9919cdfe66c;ae6440a3220849dabe9d6ecdc2e1f523;9eefabc09a7f4628b7ae104078d36dfd;ba7f12b4e7ac49e99fc49c89f30eb875;01d92e732d39466cbb8bfcf1ccc63e50;d006f78cd4134ee2a3677cde15c72450;b2ea178bf82b44b7a188c28669b29dd5;d960ae611b9345f69da57f42565ebbc3;d864517e188846e3801060ded019dd8e;201eea6239d0421284cb2dd03fd74efd;e3a3412cae2843c997862f9d18857dfc;a426430778514843ae40877f83da89f8;8e02046c031a454690efe71692d25db5;504f49055abc4d0b9865038fbc99b44b

**date à partir de laquelle ce bug du Scan est arrivé** :  06/05/2020

**exemples de fiche** : [322acd082baa465e891befa6ac2e6832](https://app.isogeo.com/groups/9eefabc09a7f4628b7ae104078d36dfd/resources/322acd082baa465e891befa6ac2e6832/history)
https://app.isogeo.com/groups/9eefabc09a7f4628b7ae104078d36dfd/resources/3e758fb8c60d4b0aa7b1528c132e2362/history

**liste exhaustive des paternes à corriger** : 
* undefined --> supprimer l'événement 
* eventDescription.intro --> supprimer l'événement 
* The dataset has been modified :
  * The length of the attribute attribute co_categorie_dossier has been changed from 2 to 2
  * The dataset has been modified
  * The coordinate system RGF93 / Lambert-93 (2154) has been set
  * The type of the attribute attribute ogc_fid has been changed from int4 to int4,PrimaryKey
  * The coordinate system was changed from RGF93 / Lambert-93 (2154) to RGF93 / Lambert-93 (2154)
* La donnée a été modifiée :
undefined

--> suspense

**Comment by leodarengosse** [comment]
L'évènement  suivant étant de retour, il faudra relancer le script une fois que CJ aura effectué la correction

La donnée a été modifiée :
undefined

**Comment by leodarengosse** [comment]
Il y a également ce type d'événement qui pose problème : 

La donnée a été modifiée :
L’emplacement de la donnée a été modifié de D:/Isogeo/Connexions à .

**Comment by leodarengosse** [comment]
The dataset has been modified :
- The precision of the attribute attribute mean_x has been changed from 1000 to 1000
- The scale of the attribute attribute mean_x has been changed from 500 to 500
- The length of the attribute attribute uid has been changed from 254 to 254

**Comment by SimonSAMPERE** [comment]
@leodarengosse la liste des groupes concernés a-t-elle évolué ?

**Comment by leodarengosse** [comment]
Il y en a surement dans beaucoup de groupe, @Mouzzi-C peux-tu regarder dans chaque groupe et faire la liste stp ? En te basant sur ta liste

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C tu peux filtrer sur la date de dernière mise à jour de la fiche pour avoir plus de chances de tomber sur une fiche concernée. Et quand tu tombe sur une fiche concernée, ça serait bien de récupérer son UUID.

**Comment by Mouzzi-C** [comment]
Il vous faut la liste des GT ou la liste de fiches à corriger dans chacun des GT ?

**Comment by SimonSAMPERE** [comment]
Il nous faut la **liste des GT** et si au passage tu peux récupérer l'UUID de quelques fiches avec des événements corrompus qui pourront servir d'exemple ça serait top

**Comment by SimonSAMPERE** [comment]
nouveau problème : 
"La donnée a été modifiée :

* 2 entités ont été ajoutées
* 2 entités ont été ajoutées
undefined
"

**Comment by SimonSAMPERE** [comment]
Concernant les évènements dont la description contient "undefined" : 
* seront supprimés ceux dont la description contient : 
  * uniquement "undefined"
  * ["La donnée a été modifiée :\n\nundefined\n"](https://app.isogeo.com/groups/0929bd0968bc4e19a6b58f65bdb4dda8/resources/c4411391c3f045b4b5c4ea16fe9d2116/history)
  * ["La donnée a été modifiée :\n\nundefined\n\r\n___\r\nLa donnée a été modifiée :\n\nundefined"](https://app.isogeo.com/groups/0929bd0968bc4e19a6b58f65bdb4dda8/resources/d37511768b0d451b931affc8d5784e09/history)
  * ["La donnée a été modifiée :\n\nundefined\n\r\n___\r\nLa donnée a été modifiée :\n\nundefined\r\n___\r\nLa donnée a été modifiée :\n\nundefined"](https://app.isogeo.com/groups/0929bd0968bc4e19a6b58f65bdb4dda8/resources/a7bdc0159d3b4d758bbba8067ca4bf62/history)
  * ["La donnée a été modifiée :\n\nundefined\n\r\n___\r\nLa donnée a été modifiée :\n\nundefined\r\n___\r\nLa donnée a été modifiée :\n\nundefined\r\n___\r\nLa donnée a été modifiée :\n\nundefined\r\n___\r\nLa donnée a été modifiée "](https://app.isogeo.com/groups/0929bd0968bc4e19a6b58f65bdb4dda8/resources/82c1f3b8e9cd4d28b87e945ad2dd5e01/history)
* seront nettoyés ceux dont la description contient également un évènement valable comme "Des entités ont été modifiées" --> le terme "undefined" sera effacé de leur description

**Comment by Mouzzi-C** [comment]
Voilà la [liste des GT](https://docs.google.com/spreadsheets/d/1U4Ku4XoddHaF64vKABv7A1zmWX-eQYqS4F0c5RtI0H8/edit#gid=0) qui ont besoin de correction d'événements.

**Comment by SimonSAMPERE** [comment]
Nouveau type d'événement corrompu : la description contient juste : 
"La donnée a été modifiée :"

**Comment by SimonSAMPERE** [comment]
Traiter uniquement les événement qui datent de 2020

**Comment by Mouzzi-C** [comment]
Ding ding dong ! Nouveau cas is in da house !

![image](https://user-images.githubusercontent.com/63340073/100246626-aa325a00-2f39-11eb-8358-b3a257e08a33.png)

Exemple trouvé dans [cette fiche](https://app.isogeo.com/groups/2f97fc44ac324d29a59ffa1ffbca080c/resources/6a9a9c20fc5a42239ff0b848baa90c33/history)

**Comment by leodarengosse** [comment]
Nouvel évènement à corriger 

> La donnée a été modifiée :
> 
> L’emplacement de la donnée a été modifié de D:/Isogeo/Connexions à .

**Comment by leodarengosse** [comment]
@SimonSAMPERE il faudrait nettoyer les évènements erronés pour [Marseille](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc)(cf. message au support), il s'agit des évènements suivants à priori

```
La donnée a été modifiée :

L’emplacement de la donnée a été modifié de D:/Isogeo/Connexions à .
```

`La donnée a été modifiée :`

Au passage, j'essaye de régler le soucis avec CJ

**Comment by leodarengosse** [comment]
Maintenant que le problème a été corrigé avec CJ, il faudrait relancer le script de nettoyage des évènements sur les groupes de travail impactés.
