### ISSUE TITLE
[MIGRATION] - CD 34 Hérault

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#72]
# Prestation de Migration - CD 34

*Groupe cible* : [d864517e188846e3801060ded019dd8e](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/dashboard/formats)
*Dossier drive* : https://drive.google.com/drive/folders/122VpViHZhBwr_Y_PXWakvsW8cnGEDleq

*Deadline* : *15/09/2020*
*Contexte* : Passage d'une base PostgreSQL/PostGIS à la même chose mais avec surcouche SDE

## Catalogues

- **M_Source** : [f6715059667541a0af49c67e57aead6c](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Af6715059667541a0af49c67e57aead6c) 
- **M_Cible**  : [476043f82bc84972a5584420c3b0a26f)](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A476043f82bc84972a5584420c3b0a26f) 

Un export du catalogue Source a été réalisé avec Isogeo2office dans le [drive](https://drive.google.com/drive/folders/122VpViHZhBwr_Y_PXWakvsW8cnGEDleq) pour constater le remplissage des champs.

## Critères de correspondance

- A priori, les noms n'ont pas changé, exemple : 
  - Source : [agriculture_sylviculture.agri_34154_taureaudecamargue_zonehumide_inao](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/resources/f35cace90a624a09a76d1754d8a02707/identification)
  - Cible : [agriculture_sylviculture.agri_34154_taureaudecamargue_zonehumide_inao](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/resources/cd3fb7befbcb4c758d24ca2954eb3edf/identification)

## Etapes

- [x] 1. Générer la table de correspondance
- [x] 2. Si certaines sources n'ont pas trouvé de cible, demander au client d'indiquer le nouveau nom où si la table n'existe plus.
- [x] 3. Migrer les fiches de métadonnées
- [x] 4. Supprimer les fiches sources après validation du client

## Règles de migration

Ne pas migrer les fiches cible qui ont été modifiées le 14/09/2020

## Suivi

- [x] table de correspondance : complétée par le client
- [x] migration : script exécuté
- [x] suppression des fiches source : script exécuté

**Comment by SimonSAMPERE** [comment]
Table de correspondance envoyée le 04/09/2020. Suite au retour du client, il faut attendre que le scan des données soit fini avant de re-générer la table et de poursuivre la migration.

**Comment by SimonSAMPERE** [comment]
A ce jour, 97 métadonnées ont été migrées. En théorie, il en reste 53 à migrer.

Après la fin du scan des données par le client, seulement 5 nouvelles correspondances ont été établies.

Pour le reste (48 fiches), il faudrait regarder avec le chef de projet (@Mouzzi-C) pourquoi la correspondance n'a pas pu être établie et éventuellement demander au client de remplir manuellement la table de correspondance ([`correspondance_27112020.csv`](https://drive.google.com/drive/folders/122VpViHZhBwr_Y_PXWakvsW8cnGEDleq)).

**Comment by Mouzzi-C** [comment]
Voilà le tableau rempli par moi et le client. 
1. Les fiches avec la remarque "Inclus dans propriétaires publics ?" n'ont pas besoin d'être migrées.
2. Voici les instructions du client quant au code couleur utilisé pour le reste : 
 * En Jaune les fiches cibles correspondantes
 * En Bleu les fiches ‘’en attente’’ il y en a deux, ce n’est vraiment pas grave si l’on doit les ressaisir
 * En Rouge les fiches de données non migrées
 * En Vert les fiches qui ont été renseignées depuis le changement de base de données. 

## Ajouté dans les règles de migration
Lors de la formation collective du 14/09/20, le client a saisi un certain nombre de fiches dans le catalogue Cible qu’il ne faudrait pas écraser en migrant les fiches sources. Elles sont toutes datées du 14 septembre 2020. 


Du coup, on a pas besoin d'attendre les deux fiches qui sont "en attente". Nous pouvons procéder à la migration si tout semble bon pou toi(@SimonSAMPERE).

**Comment by Mouzzi-C** [comment]
Voilà la version mise à jour de [la table](https://docs.google.com/spreadsheets/d/1M-DGQYqdY7s3IHtPgiceLZ9nESncaIFD/edit#gid=1943752154)

**Comment by Mouzzi-C** [comment]
En attente de la validation du client pour supprimer les fiches sources et clore la migration. Il faudra supprimer les fiches sources migrées et non migrée. Il faudra aussi supprimer la fiche source en stand-by de cette [table de correspondance](https://docs.google.com/spreadsheets/d/1-ovZKX0k-9OYImGt12x_cJAM288m10Zr/edit#gid=336001162)


La fiche [PNA - loutre - Occitanie](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/resources/35d0068a41804b09a2f6c96cd6411ba7/attributes) a été migrée manuellement. Il reste l'attribut "code" de la [fiche source](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/resources/f573383894a14b839a1157b9b12a7f8e/attributes) pour lequel je n'ai pas trouvé d'équivalent. J'ai posé la question au client par mail.

**Comment by SimonSAMPERE** [comment]
On pourra donc supprimer les 150 fiches du [catalogue M_Source](https://app.isogeo.com/groups/d864517e188846e3801060ded019dd8e/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3Af6715059667541a0af49c67e57aead6c) dès qu'on aura eu la validation du client.

**Comment by Mouzzi-C** [comment]
Go ! Go ! Go !

**Comment by SimonSAMPERE** [comment]
Les 150 fiches source ont été supprimées.

**Comment by Mouzzi-C** [comment]
Mail envoyé à l'équipe commerciale pour facturer le client. Je ferme ce ticket !!
