### ISSUE TITLE
[MIGRATION] - Ville de Niort

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#92]
# Prestation de Migration - Ville de Niort

Groupe Source : [6325d0c753214e84b850f9919cdfe66c](https://app.isogeo.com/groups/6325d0c753214e84b850f9919cdfe66c/dashboard/formats)
Groupe cible : [51e8a14a3bd94e79b57b166e142377b0](https://app.isogeo.com/groups/51e8a14a3bd94e79b57b166e142377b0/dashboard/formats)

Deadline : En stand-by pour le moment. 

## Contexte 

* Migration qui date de septembre **2018**. Wait, WHAT ??
* En 2018, le CA de Niort et la Ville de Niort ont fusionnées, le service SIG également. 
* Toutes les données de la CA Niort sont rapatriées à la Ville de Niort. 
* La Ville de Niort souhaite conserver le travail de documentation effectué par le CA Niort, c’est pourquoi une migration est demandée. 
* Point du 30/10/2020 ajourné à la semaine du 9 novembre (à cause du confinement !!) 

## Catalogues

- le catalogue Source existe : A migrer CAN : [02a4aebfa42743c990f4a4cde6ba4553](https://app.isogeo.com/groups/6325d0c753214e84b850f9919cdfe66c/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A02a4aebfa42743c990f4a4cde6ba4553)
- En guise de catalogue cible, on peut chercher des correpondances dans l'intégralité du groupe cible [51e8a14a3bd94e79b57b166e142377b0](https://app.isogeo.com/groups/51e8a14a3bd94e79b57b166e142377b0/dashboard/formats)
(le catalogue Cible existe mais n'est pas encore complètement rempli : Cible CAN [13af66537426401aa6394399f53daf28](https://app.isogeo.com/groups/51e8a14a3bd94e79b57b166e142377b0/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A13af66537426401aa6394399f53daf28))

## Critères de correspondance

* Les métadonnées de type vector-dataset doivent être migrées vers les fiches créées par le scan de la Ville de Niort. 
  * Le nom des fiches sources est préfixé de *IMACAD_ENCOURS.*  Ex : **IMACAD_ENCOURS.PARCELLECOMMUNALE_2013**
  * Le nom des fiches cibles est préfixé de *CANMAIRIE.*  Ex : **CANMAIRIE.FRICHE_OCS** ou *IMACAD.*  Ex : **IMACAD.TXT_LIE**
* Les métadonnées de type raster-dataset doivent être dupliquées en l’état vers le GT Ville de Niort.

## Règles de migration (si nécessaire)

1. Ne pas migrer la documentation des fiches préfixées de *IMACAD_ENCOURS.*.
2. Ne pas migrer les fiches sources lorsque les cibles sont documentées.

## Suivi

- [x] Préparation des catalogues source et cible : Scan installé
- [x] table de correspondance : `correspondances.csv` ([ici](https://drive.google.com/drive/folders/1OjIbkvGb1RXtrlKP4ZmS40BKT4WUTrsQ))
- [x] migration : 
  * les fiches raster sont prêtes à être dupliquées
  * en attente de la table pour les fiches vecteur
- [ ] suppression des fiches source :

**Comment by SimonSAMPERE** [comment]
Carlo, est-ce-qu'on a du nouveau concernant cette presta ?

**Comment by Mouzzi-C** [comment]
J'ai pas de nouvelles du client. Je vais relancer et te tiens au courant dès qu'il y a du nouveau.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, j'ai généré une table de correspondance (`correspondances.csv`) [ici](https://drive.google.com/drive/folders/1OjIbkvGb1RXtrlKP4ZmS40BKT4WUTrsQ) : 
* j'ai quand même pu établir 46 correspondances pour 50 fiches source **sans appliquer le critère de correspondance**
* les 4 fiches source pour lesquelles la correspondance n'a pas pu être établi ne possèdent pas de nom, la correspondance ne pourra donc pas être établie automatiquement, apparemment il s'agit des fiches Raster qui devront être "dupliquées en l'état"

**Comment by Mouzzi-C** [comment]
J'ai retrouvé les 4 dernières fiches et ai mis à jour [la table](https://docs.google.com/spreadsheets/d/10I5FCYzT_JEwnuvpx4wwkfr0gjBIb94H/edit?usp=drive_web&ouid=101482341446450533670&rtpof=true). 

On dirait effectivement qu'une migration avait déjà été effectuée. Je vais informer le client et te tenir au courant.

**Comment by SimonSAMPERE** [comment]
J'ai regénéré une table en appliquant le critère de correspondance et en excluant le les fiches du catalogue source partagé au groupe cible. 29 correspondances ont pu être établies automatiquement. La table se trouve [ici](https://drive.google.com/drive/folders/1OjIbkvGb1RXtrlKP4ZmS40BKT4WUTrsQ), je l'ai appelé `correspondances_bis.csv`

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C on en est où de cette presta ?

**Comment by Mouzzi-C** [comment]
On est bloqué à cause de la licence FME du client. Ils ont une professional edition et il leur faut une Esri edition. Je te dis dès que j'ai des nouvelles

**Comment by SimonSAMPERE** [comment]
Ah ouai j'avais zappé, dans ce cas on reste en stand-by.

**Comment by SimonSAMPERE** [comment]
J'ai relancé le script de matching, on est toujours à 29 correspondances.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C j'ai migré 92 fiches aujourd'hui. 

Mais ya deux problèmes : 
* J'ai aussi migré les fiches préfixées de "IMACAD_ENCOURS." puisqu'elles apparaissaient dans la table de correspondance de la cliente et que j'avais oublié qu'il fallait les exclure. Mais j'ai fait un backup donc on pourra revenir en arrière si besoin.
* Je n'ai pas pu migrer les contacts et les catalogues puisque je n'avais pas de correspondances entre ceux du groupe source et ceux du groupe cible.

On en reparle à mon retour de congés si tu n'es pas en congés toi aussi

**Comment by Mouzzi-C** [comment]
La cliente à pris le temps de modifier la table de correspondance en supprimant toutes les données qu'il ne fallait pas migrer t'as bien fait de migrer les données "IMACAD_ENCOURS".

En ce qui concerne le contact et catalogue, je vais voir ça avec la cliente directement et je les ajouterai directement. 

Je te tiens au courant quand c'est fait pour que tu puisses fermer l'issue à ton retour.

**Comment by Mouzzi-C** [comment]
C'est bon pour les contacts et le catalogue. La cliente à vérifié les fiches. 

Je te laisse fermer l'issue. :-)

**Comment by SimonSAMPERE** [comment]
Super boulot, merci @Mouzzi-C
