### ISSUE TITLE
Remplacer le lien du logo IGN dans le résumé

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/migrations-toolbelt#93]
Le lien du logo IGN du résumé de plusieurs fiches dans plusieurs groupes de travail n'est plus valide. 

Il faut rechercher le lien suivant : [http://www.ign.fr/sites/all/themes/ign_portail/logo.png](http://www.ign.fr/sites/all/themes/ign_portail/logo.png) et le remplacer par le lien suivant [https://www.ensg.eu/-MEP0-/apv/logo_IGN.png](https://www.ensg.eu/-MEP0-/apv/logo_IGN.png)

Voilà la liste des GT qui contiennent des fiches à modifier : 

* IGN-F : [504f49055abc4d0b9865038fbc99b44b](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/dashboard/formats)
* Département Eure-et-Loir : [53b3ee084b71407fad63684a53e28579](https://app.isogeo.com/groups/53b3ee084b71407fad63684a53e28579/dashboard/formats)
* Communauté Urbaine de Dunkerque : [32af72140afe4b93b7ce4ca4b7de8df8](https://app.isogeo.com/groups/32af72140afe4b93b7ce4ca4b7de8df8/dashboard/formats)
* Métropole de Rouen Normandie : [80e2a30f471e43f1845a33d98e6a42e3](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/dashboard/formats)
* Métropole Aix-Marseille Provence : [e3a3412cae2843c997862f9d18857dfc](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/dashboard/formats)

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C, le script a détecté 524 fiches de métadonnées qui contiennent l'ancien lien dans leur extrait : 

* IGN-F ([504f49055abc4d0b9865038fbc99b44b](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/dashboard/formats)) - **293 fiches**
* Département Eure-et-Loir ([53b3ee084b71407fad63684a53e28579](https://app.isogeo.com/groups/53b3ee084b71407fad63684a53e28579/dashboard/formats)) - **49 fiches**
* Communauté Urbaine de Dunkerque ([32af72140afe4b93b7ce4ca4b7de8df8](https://app.isogeo.com/groups/32af72140afe4b93b7ce4ca4b7de8df8/dashboard/formats)) - **0 fiches**
* Métropole de Rouen Normandie ([80e2a30f471e43f1845a33d98e6a42e3](https://app.isogeo.com/groups/80e2a30f471e43f1845a33d98e6a42e3/dashboard/formats)) - **126 fiches**
* Métropole Aix-Marseille Provence ([e3a3412cae2843c997862f9d18857dfc](https://app.isogeo.com/groups/e3a3412cae2843c997862f9d18857dfc/dashboard/formats)) - **56 fiches**

**Comment by Mouzzi-C** [comment]
* Est-ce-qu'il faudrait regarder dans d'autres champs que l'extrait ?
  * Non c'est une image qu'on met juste dans le résumé.
* Est-ce-que c'est normal que j'en trouve aucun dans le groupe de Dunkerque ?
  * Non. Voilà un exemple de fiche qui contient ce lien : [4ecce8fdf78847b7b4ddd778dcf77ccd](https://app.isogeo.com/groups/32af72140afe4b93b7ce4ca4b7de8df8/resources/4ecce8fdf78847b7b4ddd778dcf77ccd/identification)

**Comment by SimonSAMPERE** [comment]
Au temps pour moi je pense que c'est parce que je suis pas dans le groupe de travail. Le script détecte **52** fiches dans le groupe Dunkerque ce qui fait **576** fiches en tout.

SI c'est ok je lance le script ce soir.

**Comment by Mouzzi-C** [comment]
yes vas-y 👍

**Comment by SimonSAMPERE** [comment]
En fait il faudrait remplacer "![Texte alternatif](http://www.ign.fr/sites/all/themes/ign_portail/logo.png "Logo de l'IGN")" par "![Logo de l'IGN](https://www.ensg.eu/-MEP0-/apv/logo_IGN.png)
