### ISSUE TITLE
Ajouter un nom aux fiches de métadonnées de référence qui n'en ont pas

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/migrations-toolbelt#94]
@Mouzzi-C il me faudrait un tableau pour récapituler le nom qu'on veut donner aux fiches de métadonnées de référence qui ont été créées manuellement. Ce tableau pourrait contenir juste 3 colonnes :
* uuid du groupe de travail de la fiche
* uuid de la fiche
* nom qu'on veut donner à la fiche

Ensuite, si je peux créer, via le sdk-python, une fiche avec un nom, je m'occuperait de faire une migration. Sinon il faudra peut-être scanner des données "factices" qui auront déjà le nom qu'on veut donner.

**Comment by Mouzzi-C** [comment]
Voilà la [table de correspondance](https://docs.google.com/spreadsheets/d/1vnJcrxZwcsM4ZL86DxgymDkeHTLSfPFg-Jukns5I-3s/edit#gid=0) des données vecteurs auxquelles ils faut ajouter un nom

**Comment by SimonSAMPERE** [comment]
C'est fait, je te laisse vérifier en te basant sur [ce tableau](https://docs.google.com/spreadsheets/d/1XCx2ACv3RlMStl6utD_omANz2cAJlmvb/edit?usp=drive_web&ouid=107937934076694281279&rtpof=true).

Toutes les fiches créées sont dans un catalogue ["M_Migrated"](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A5c743581c7724f69bdab6b542d003b7a) qu'on pourra supprimer une fois que ça sera validé.

J'ai aussi créé un catalogue ["M_to_delte"](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A61199303db6c466ba47501cb00a3fd01). Pour l'instant il contient des doublons créés pendant que je faisais des tests. Je te propose d'y associer les fiche sources au fur et à mesure de ta vérification. De cette manière on pourra facilement toutes les supprimer (les sources et les doublons) lorsque le bug de suppression sera corrigé.

**Comment by Mouzzi-C** [comment]
J'ai fait le tour, ça m'a l'air tout bon. Je t'ai mis les fiches sources dans le catalogue[M_to_delete](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=title&od=asc&q=catalog%3A61199303db6c466ba47501cb00a3fd01).

**Comment by SimonSAMPERE** [comment]
Modifier le nom d'une fiche de la BD Carto 4

**Comment by Mouzzi-C** [comment]
Il y a ddeux fiches du catalogue [BD Catrto 4.0](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A64571133cc4148baaad15c400e255fb4) à modifier : 

* [b077525b7e16457d9b7a942e93b653ce](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/b077525b7e16457d9b7a942e93b653ce/identification)
  * ARRONDISSEMENT devient ARRONDISSEMENT_DEPARTEMENTAL
* [f19d73d0e8524472a9f308112d4c1bd1](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/f19d73d0e8524472a9f308112d4c1bd1/identification)
  * ZONE_HABITAT devient ZONE_HABITAT_MAIRIE

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C , le script a été lancé, pour chacune des deux fiches, une fiche a été crées, elle est identique à l'exception du nom qui a été modifié pour correspondre à la demande. Je te laisse vérifier que le duplicata est identique à l'original et supprimer l'original : 
* [b077525b7e16457d9b7a942e93b653ce](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/b077525b7e16457d9b7a942e93b653ce/identification) ARRONDISSEMENT --> [418db64db47f44a989604e700e4cc125](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/418db64db47f44a989604e700e4cc125/identification) ARRONDISSEMENT_DEPARTEMENTAL
* [f19d73d0e8524472a9f308112d4c1bd1](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/f19d73d0e8524472a9f308112d4c1bd1/identification) ZONE_HABITAT --> [014c9126523b4dcb8aa7ac9c15972497](https://app.isogeo.com/groups/504f49055abc4d0b9865038fbc99b44b/resources/014c9126523b4dcb8aa7ac9c15972497/identification) ZONE_HABITAT_MAIRIE

**Comment by Mouzzi-C** [comment]
C'est tout bon ! J'ai supprimé les deux fiches sources.
