### ISSUE TITLE
[MIGRATION] - Calvados

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#95]
# Prestation de Migration - Département du Calvados

Groupe cible : [0c36eef4b81d4f1ca2db0465721feb73](https://app.isogeo.com/groups/0c36eef4b81d4f1ca2db0465721feb73/)

Deadline : Mi-décembre

Contexte : Des doublons ont été créés par les scans du [21 octobre 2020](https://scan.isogeo.com/g/0c36eef4b81d4f1ca2db0465721feb73/entrypoints/5c87b8b84a50fb01bca40607/requests/5f8fb61d6ab16b362228a554) et du [6 novembre](https://scan.isogeo.com/g/0c36eef4b81d4f1ca2db0465721feb73/entrypoints/5c87b8b84a50fb01bca40607/requests/5fa5cdaf6ab16b362228a866)

## Catalogues

Les catalogues n'existent pas : il faudrait générer la table de correspondance en détectant les noms de tables identiques. Les fiches sources étant celles créées avant la date du 20 octobre et les fiches cibles après.

## Critères de correspondance

Noms de table strictement identiques.

## Règles de migration (si nécessaire)

RAS

## Suivi

- [x] table de correspondance : [ici](https://drive.google.com/drive/folders/1Wl_z_2hivIJ0AX0mClWJB4qZpKHpN-d-)
- [x] migration : 
- [x] suppression des fiches source :

**Comment by SimonSAMPERE** [comment]
148 matchs entre 753 sources et 246 cibles

**Comment by leodarengosse** [comment]
@SimonSAMPERE peux-tu regarder si il y a de nouveau des doublons et les nettoyer stp ?

**Comment by SimonSAMPERE** [comment]
@leodarengosse effectivement j'ai trouvé 145 doublons, je m'en occupe dès que possible.

**Comment by SimonSAMPERE** [comment]
j'ai migré les doublons conformément à [cette table](https://github.com/isogeo/migrations-toolbelt/files/6420874/migrated_1620127986.480555.zip), les fiches cibles (les plus récemment créées par le scan sont dans [ce catalogue](https://app.isogeo.com/groups/0c36eef4b81d4f1ca2db0465721feb73/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A8a078afacde0425696b0da501e965cc6).

Par contre ya eu un soucis avec les événements de publication antérieur à la date de création de la fiche qui n'ont pas pu être migrés dns les cibles car le SDK ne me permet pas de créer un évéenemnt plus ancien que celui de la date de création

**Comment by leodarengosse** [comment]
ah oui quand même ça en fait des doublons... relou pour les évènements mais ça parait logique. Il y en a beaucoup ?

**Comment by SimonSAMPERE** [comment]
68 je crois

**Comment by SimonSAMPERE** [comment]
le tableau s'appelle [`doublons_pb_events.xlsx`](https://docs.google.com/spreadsheets/d/1fdfN4GhoR_435LEM7DiSVwf2ICjwfd-F/edit#gid=2137504938), il est dans "G:\Mon Drive\Racine Isogeo\Clients\54_CD14_CALVADOS\02_REALISATION\07_CATALOGAGE\Migration"

**Comment by Mouzzi-C** [comment]
Le client a détecté de nouveaux doublons créés suite au scan du 6 juillet. Je réouvre l'issue pour créer une table de correspondance et migrer la documentation.

**Comment by SimonSAMPERE** [comment]
@Mouzzi-C , j'ai relancé une table de correspondance, apparemment il existe 40 doublons. J'ai mis la table dans le Google drive : G:\Mon Drive\Racine Isogeo\CLIENTS\54_CD14_CALVADOS\02_REALISATION\07_CATALOGAGE\Migration\doublons_2021.xlsx

Apparemment les doublons datent de mai et non du 6 juillet. Je te laisse checker si besoin et me dire si je les migre directos ou si on discute avec le client avant.

**Comment by Mouzzi-C** [comment]
Ok ça marche, tiens moi au courant pour que je communique avec la cliente.

**Comment by SimonSAMPERE** [comment]
Finalement j'ai réussi avec l'aide de Julie à déterminer les fiches à supprimer, je migre ça dans la journée.

**Comment by SimonSAMPERE** [comment]
C'est bon c'est fait !
