### ISSUE TITLE
[MIGRATION] - CD 94

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/migrations-toolbelt#96]
# Prestation de Migration - CD 94

Groupe cible : [3dc29ce36d9d4b969a08e8669301c751](https://app.isogeo.com/groups/3dc29ce36d9d4b969a08e8669301c751/)

Deadline : Mi-décembre

Contexte : Des doublons ont été créés par le scan du [26 novembre](https://scan.isogeo.com/g/3dc29ce36d9d4b969a08e8669301c751/entrypoints/5f9fe3bd6ab16b362228a773/requests/5fbfded3b8582e9584b32b7c) suites aux manipulations du point d'entrée pour scanner la base Oracle.

## Catalogues

Catalogues M_Cible : [020db09a535e472e87080cb1119c5f09](https://app.isogeo.com/groups/3dc29ce36d9d4b969a08e8669301c751/inventory/search?p=1&ob=%23relevance&od=des&q=catalog%3A020db09a535e472e87080cb1119c5f09)

Le catalogues Source n'existent pas : il faudrait générer la table de correspondance en détectant les noms de tables identiques. Les fiches sources étant celles créées avant la date du 26 novembre et les fiches cibles celles du catalogue M_Cible.

## Critères de correspondance

Noms de table strictement identiques.

## Règles de migration (si nécessaire)

RAS

## Suivi

- [x] table de correspondance : 
- [x] migration : 
- [x] suppression des fiches source :

**Comment by SimonSAMPERE** [comment]
684 correspondances entre 1641 sources  699 cibles
